// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockConfigLoader is an autogenerated mock type for the ConfigLoader type
type MockConfigLoader struct {
	mock.Mock
}

type MockConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigLoader) EXPECT() *MockConfigLoader_Expecter {
	return &MockConfigLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: configDir
func (_m *MockConfigLoader) Load(configDir string) error {
	ret := _m.Called(configDir)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(configDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - configDir string
func (_e *MockConfigLoader_Expecter) Load(configDir interface{}) *MockConfigLoader_Load_Call {
	return &MockConfigLoader_Load_Call{Call: _e.mock.On("Load", configDir)}
}

func (_c *MockConfigLoader_Load_Call) Run(run func(configDir string)) *MockConfigLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_Load_Call) Return(_a0 error) *MockConfigLoader_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigLoader_Load_Call) RunAndReturn(run func(string) error) *MockConfigLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigLoader creates a new instance of MockConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigLoader {
	mock := &MockConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
