// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	configs "proxynd/configs"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *MockService
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: _m}
}

// GetAptConfig provides a mock function with given fields: ctx
func (_m *MockService) GetAptConfig(ctx context.Context) (*configs.AptProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.AptProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.AptProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.AptProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalConfig provides a mock function with given fields: ctx
func (_m *MockService) GetGlobalConfig(ctx context.Context) (*configs.GlobalConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.GlobalConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.GlobalConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.GlobalConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMavenConfig provides a mock function with given fields: ctx
func (_m *MockService) GetMavenConfig(ctx context.Context) (*configs.MavenProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.MavenProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.MavenProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.MavenProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNpmConfig provides a mock function with given fields: ctx
func (_m *MockService) GetNpmConfig(ctx context.Context) (*configs.NpmProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.NpmProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.NpmProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.NpmProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDockerConfig provides a mock function with given fields: ctx
func (_m *MockService) GetDockerConfig(ctx context.Context) (*configs.DockerProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.DockerProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.DockerProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.DockerProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipConfig provides a mock function with given fields: ctx
func (_m *MockService) GetPipConfig(ctx context.Context) (*configs.PipProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.PipProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.PipProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.PipProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYumConfig provides a mock function with given fields: ctx
func (_m *MockService) GetYumConfig(ctx context.Context) (*configs.YumProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.YumProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.YumProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.YumProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApkConfig provides a mock function with given fields: ctx
func (_m *MockService) GetApkConfig(ctx context.Context) (*configs.ApkProxyConfig, error) {
	ret := _m.Called(ctx)

	var r0 *configs.ApkProxyConfig
	if rf, ok := ret.Get(0).(func(context.Context) *configs.ApkProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.ApkProxyConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAll provides a mock function with given fields: ctx
func (_m *MockService) ValidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reload provides a mock function with given fields: ctx
func (_m *MockService) Reload(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
