// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	configs "proxynd/configs"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetApkConfig provides a mock function with given fields: ctx
func (_m *MockService) GetApkConfig(ctx context.Context) (*configs.ApkProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApkConfig")
	}

	var r0 *configs.ApkProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.ApkProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.ApkProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.ApkProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetApkConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApkConfig'
type MockService_GetApkConfig_Call struct {
	*mock.Call
}

// GetApkConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetApkConfig(ctx interface{}) *MockService_GetApkConfig_Call {
	return &MockService_GetApkConfig_Call{Call: _e.mock.On("GetApkConfig", ctx)}
}

func (_c *MockService_GetApkConfig_Call) Run(run func(ctx context.Context)) *MockService_GetApkConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetApkConfig_Call) Return(_a0 *configs.ApkProxyConfig, _a1 error) *MockService_GetApkConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetApkConfig_Call) RunAndReturn(run func(context.Context) (*configs.ApkProxyConfig, error)) *MockService_GetApkConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetAptConfig provides a mock function with given fields: ctx
func (_m *MockService) GetAptConfig(ctx context.Context) (*configs.AptProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAptConfig")
	}

	var r0 *configs.AptProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.AptProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.AptProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.AptProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAptConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAptConfig'
type MockService_GetAptConfig_Call struct {
	*mock.Call
}

// GetAptConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAptConfig(ctx interface{}) *MockService_GetAptConfig_Call {
	return &MockService_GetAptConfig_Call{Call: _e.mock.On("GetAptConfig", ctx)}
}

func (_c *MockService_GetAptConfig_Call) Run(run func(ctx context.Context)) *MockService_GetAptConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetAptConfig_Call) Return(_a0 *configs.AptProxyConfig, _a1 error) *MockService_GetAptConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAptConfig_Call) RunAndReturn(run func(context.Context) (*configs.AptProxyConfig, error)) *MockService_GetAptConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetDockerConfig provides a mock function with given fields: ctx
func (_m *MockService) GetDockerConfig(ctx context.Context) (*configs.DockerProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDockerConfig")
	}

	var r0 *configs.DockerProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.DockerProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.DockerProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.DockerProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDockerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDockerConfig'
type MockService_GetDockerConfig_Call struct {
	*mock.Call
}

// GetDockerConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetDockerConfig(ctx interface{}) *MockService_GetDockerConfig_Call {
	return &MockService_GetDockerConfig_Call{Call: _e.mock.On("GetDockerConfig", ctx)}
}

func (_c *MockService_GetDockerConfig_Call) Run(run func(ctx context.Context)) *MockService_GetDockerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetDockerConfig_Call) Return(_a0 *configs.DockerProxyConfig, _a1 error) *MockService_GetDockerConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDockerConfig_Call) RunAndReturn(run func(context.Context) (*configs.DockerProxyConfig, error)) *MockService_GetDockerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalConfig provides a mock function with given fields: ctx
func (_m *MockService) GetGlobalConfig(ctx context.Context) (*configs.GlobalConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalConfig")
	}

	var r0 *configs.GlobalConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.GlobalConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.GlobalConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.GlobalConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalConfig'
type MockService_GetGlobalConfig_Call struct {
	*mock.Call
}

// GetGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetGlobalConfig(ctx interface{}) *MockService_GetGlobalConfig_Call {
	return &MockService_GetGlobalConfig_Call{Call: _e.mock.On("GetGlobalConfig", ctx)}
}

func (_c *MockService_GetGlobalConfig_Call) Run(run func(ctx context.Context)) *MockService_GetGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetGlobalConfig_Call) Return(_a0 *configs.GlobalConfig, _a1 error) *MockService_GetGlobalConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetGlobalConfig_Call) RunAndReturn(run func(context.Context) (*configs.GlobalConfig, error)) *MockService_GetGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetMavenConfig provides a mock function with given fields: ctx
func (_m *MockService) GetMavenConfig(ctx context.Context) (*configs.MavenProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMavenConfig")
	}

	var r0 *configs.MavenProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.MavenProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.MavenProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.MavenProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMavenConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMavenConfig'
type MockService_GetMavenConfig_Call struct {
	*mock.Call
}

// GetMavenConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMavenConfig(ctx interface{}) *MockService_GetMavenConfig_Call {
	return &MockService_GetMavenConfig_Call{Call: _e.mock.On("GetMavenConfig", ctx)}
}

func (_c *MockService_GetMavenConfig_Call) Run(run func(ctx context.Context)) *MockService_GetMavenConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMavenConfig_Call) Return(_a0 *configs.MavenProxyConfig, _a1 error) *MockService_GetMavenConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMavenConfig_Call) RunAndReturn(run func(context.Context) (*configs.MavenProxyConfig, error)) *MockService_GetMavenConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetNpmConfig provides a mock function with given fields: ctx
func (_m *MockService) GetNpmConfig(ctx context.Context) (*configs.NpmProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNpmConfig")
	}

	var r0 *configs.NpmProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.NpmProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.NpmProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.NpmProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetNpmConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNpmConfig'
type MockService_GetNpmConfig_Call struct {
	*mock.Call
}

// GetNpmConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetNpmConfig(ctx interface{}) *MockService_GetNpmConfig_Call {
	return &MockService_GetNpmConfig_Call{Call: _e.mock.On("GetNpmConfig", ctx)}
}

func (_c *MockService_GetNpmConfig_Call) Run(run func(ctx context.Context)) *MockService_GetNpmConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetNpmConfig_Call) Return(_a0 *configs.NpmProxyConfig, _a1 error) *MockService_GetNpmConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetNpmConfig_Call) RunAndReturn(run func(context.Context) (*configs.NpmProxyConfig, error)) *MockService_GetNpmConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetPipConfig provides a mock function with given fields: ctx
func (_m *MockService) GetPipConfig(ctx context.Context) (*configs.PipProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPipConfig")
	}

	var r0 *configs.PipProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.PipProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.PipProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.PipProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetPipConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPipConfig'
type MockService_GetPipConfig_Call struct {
	*mock.Call
}

// GetPipConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetPipConfig(ctx interface{}) *MockService_GetPipConfig_Call {
	return &MockService_GetPipConfig_Call{Call: _e.mock.On("GetPipConfig", ctx)}
}

func (_c *MockService_GetPipConfig_Call) Run(run func(ctx context.Context)) *MockService_GetPipConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetPipConfig_Call) Return(_a0 *configs.PipProxyConfig, _a1 error) *MockService_GetPipConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetPipConfig_Call) RunAndReturn(run func(context.Context) (*configs.PipProxyConfig, error)) *MockService_GetPipConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetYumConfig provides a mock function with given fields: ctx
func (_m *MockService) GetYumConfig(ctx context.Context) (*configs.YumProxyConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetYumConfig")
	}

	var r0 *configs.YumProxyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*configs.YumProxyConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *configs.YumProxyConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configs.YumProxyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetYumConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYumConfig'
type MockService_GetYumConfig_Call struct {
	*mock.Call
}

// GetYumConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetYumConfig(ctx interface{}) *MockService_GetYumConfig_Call {
	return &MockService_GetYumConfig_Call{Call: _e.mock.On("GetYumConfig", ctx)}
}

func (_c *MockService_GetYumConfig_Call) Run(run func(ctx context.Context)) *MockService_GetYumConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetYumConfig_Call) Return(_a0 *configs.YumProxyConfig, _a1 error) *MockService_GetYumConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetYumConfig_Call) RunAndReturn(run func(context.Context) (*configs.YumProxyConfig, error)) *MockService_GetYumConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function with given fields: ctx
func (_m *MockService) Reload(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockService_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Reload(ctx interface{}) *MockService_Reload_Call {
	return &MockService_Reload_Call{Call: _e.mock.On("Reload", ctx)}
}

func (_c *MockService_Reload_Call) Run(run func(ctx context.Context)) *MockService_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Reload_Call) Return(_a0 error) *MockService_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Reload_Call) RunAndReturn(run func(context.Context) error) *MockService_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAll provides a mock function with given fields: ctx
func (_m *MockService) ValidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ValidateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAll'
type MockService_ValidateAll_Call struct {
	*mock.Call
}

// ValidateAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ValidateAll(ctx interface{}) *MockService_ValidateAll_Call {
	return &MockService_ValidateAll_Call{Call: _e.mock.On("ValidateAll", ctx)}
}

func (_c *MockService_ValidateAll_Call) Run(run func(ctx context.Context)) *MockService_ValidateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ValidateAll_Call) Return(_a0 error) *MockService_ValidateAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ValidateAll_Call) RunAndReturn(run func(context.Context) error) *MockService_ValidateAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
