# .air.simple.toml

# Configurations for simple development
root = "."

[build]
cmd = "go build -o ./bin/app main.go"
bin = "./bin/app"

[log]
level = "debug"

[watch]
include = ["**/*.go", "**/*.html", "**/*.yaml"]
exclude = ["tmp", "vendor", "bin"]
