// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheService is an autogenerated mock type for the CacheService type
type MockCacheService struct {
	mock.Mock
}

type MockCacheService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheService) EXPECT() *MockCacheService_Expecter {
	return &MockCacheService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockCacheService) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheService_Expecter) Delete(ctx interface{}, key interface{}) *MockCacheService_Delete_Call {
	return &MockCacheService_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCacheService_Delete_Call) Run(run func(ctx context.Context, key string)) *MockCacheService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheService_Delete_Call) Return(_a0 error) *MockCacheService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockCacheService) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheService_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCacheService_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheService_Expecter) Exists(ctx interface{}, key interface{}) *MockCacheService_Exists_Call {
	return &MockCacheService_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockCacheService_Exists_Call) Run(run func(ctx context.Context, key string)) *MockCacheService_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheService_Exists_Call) Return(_a0 bool, _a1 error) *MockCacheService_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheService_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCacheService_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockCacheService) Get(ctx context.Context, key string) (io.ReadCloser, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCacheService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheService_Expecter) Get(ctx interface{}, key interface{}) *MockCacheService_Get_Call {
	return &MockCacheService_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheService_Get_Call) Run(run func(ctx context.Context, key string)) *MockCacheService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheService_Get_Call) Return(_a0 io.ReadCloser, _a1 bool, _a2 error) *MockCacheService_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCacheService_Get_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, bool, error)) *MockCacheService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, content
func (_m *MockCacheService) Put(ctx context.Context, key string, content io.Reader) error {
	ret := _m.Called(ctx, key, content)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, key, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheService_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockCacheService_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - content io.Reader
func (_e *MockCacheService_Expecter) Put(ctx interface{}, key interface{}, content interface{}) *MockCacheService_Put_Call {
	return &MockCacheService_Put_Call{Call: _e.mock.On("Put", ctx, key, content)}
}

func (_c *MockCacheService_Put_Call) Run(run func(ctx context.Context, key string, content io.Reader)) *MockCacheService_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockCacheService_Put_Call) Return(_a0 error) *MockCacheService_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheService_Put_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockCacheService_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheService creates a new instance of MockCacheService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheService {
	mock := &MockCacheService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
