// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigService is an autogenerated mock type for the ConfigService type
type MockConfigService struct {
	mock.Mock
}

type MockConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigService) EXPECT() *MockConfigService_Expecter {
	return &MockConfigService_Expecter{mock: &_m.Mock}
}

// GetGlobalConfig provides a mock function with given fields: ctx
func (_m *MockConfigService) GetGlobalConfig(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalConfig")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigService_GetGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalConfig'
type MockConfigService_GetGlobalConfig_Call struct {
	*mock.Call
}

// GetGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigService_Expecter) GetGlobalConfig(ctx interface{}) *MockConfigService_GetGlobalConfig_Call {
	return &MockConfigService_GetGlobalConfig_Call{Call: _e.mock.On("GetGlobalConfig", ctx)}
}

func (_c *MockConfigService_GetGlobalConfig_Call) Run(run func(ctx context.Context)) *MockConfigService_GetGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigService_GetGlobalConfig_Call) Return(_a0 interface{}, _a1 error) *MockConfigService_GetGlobalConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigService_GetGlobalConfig_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *MockConfigService_GetGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetProxyConfig provides a mock function with given fields: ctx, proxyType
func (_m *MockConfigService) GetProxyConfig(ctx context.Context, proxyType string) (interface{}, error) {
	ret := _m.Called(ctx, proxyType)

	if len(ret) == 0 {
		panic("no return value specified for GetProxyConfig")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, proxyType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, proxyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, proxyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigService_GetProxyConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProxyConfig'
type MockConfigService_GetProxyConfig_Call struct {
	*mock.Call
}

// GetProxyConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - proxyType string
func (_e *MockConfigService_Expecter) GetProxyConfig(ctx interface{}, proxyType interface{}) *MockConfigService_GetProxyConfig_Call {
	return &MockConfigService_GetProxyConfig_Call{Call: _e.mock.On("GetProxyConfig", ctx, proxyType)}
}

func (_c *MockConfigService_GetProxyConfig_Call) Run(run func(ctx context.Context, proxyType string)) *MockConfigService_GetProxyConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConfigService_GetProxyConfig_Call) Return(_a0 interface{}, _a1 error) *MockConfigService_GetProxyConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigService_GetProxyConfig_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockConfigService_GetProxyConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadConfig provides a mock function with given fields: ctx
func (_m *MockConfigService) ReloadConfig(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigService_ReloadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadConfig'
type MockConfigService_ReloadConfig_Call struct {
	*mock.Call
}

// ReloadConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigService_Expecter) ReloadConfig(ctx interface{}) *MockConfigService_ReloadConfig_Call {
	return &MockConfigService_ReloadConfig_Call{Call: _e.mock.On("ReloadConfig", ctx)}
}

func (_c *MockConfigService_ReloadConfig_Call) Run(run func(ctx context.Context)) *MockConfigService_ReloadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigService_ReloadConfig_Call) Return(_a0 error) *MockConfigService_ReloadConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigService_ReloadConfig_Call) RunAndReturn(run func(context.Context) error) *MockConfigService_ReloadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigService creates a new instance of MockConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigService {
	mock := &MockConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
