// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "proxynd/internal/services/proxy"

	mock "github.com/stretchr/testify/mock"
)

// MockProxyService is an autogenerated mock type for the ProxyService type
type MockProxyService struct {
	mock.Mock
}

type MockProxyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProxyService) EXPECT() *MockProxyService_Expecter {
	return &MockProxyService_Expecter{mock: &_m.Mock}
}

// GetProxyType provides a mock function with no fields
func (_m *MockProxyService) GetProxyType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProxyType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProxyService_GetProxyType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProxyType'
type MockProxyService_GetProxyType_Call struct {
	*mock.Call
}

// GetProxyType is a helper method to define mock.On call
func (_e *MockProxyService_Expecter) GetProxyType() *MockProxyService_GetProxyType_Call {
	return &MockProxyService_GetProxyType_Call{Call: _e.mock.On("GetProxyType")}
}

func (_c *MockProxyService_GetProxyType_Call) Run(run func()) *MockProxyService_GetProxyType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProxyService_GetProxyType_Call) Return(_a0 string) *MockProxyService_GetProxyType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyService_GetProxyType_Call) RunAndReturn(run func() string) *MockProxyService_GetProxyType_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRequest provides a mock function with given fields: ctx, req
func (_m *MockProxyService) HandleRequest(ctx context.Context, req proxy.ProxyRequest) (*proxy.ProxyResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleRequest")
	}

	var r0 *proxy.ProxyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.ProxyRequest) (*proxy.ProxyResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.ProxyRequest) *proxy.ProxyResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ProxyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.ProxyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProxyService_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type MockProxyService_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req proxy.ProxyRequest
func (_e *MockProxyService_Expecter) HandleRequest(ctx interface{}, req interface{}) *MockProxyService_HandleRequest_Call {
	return &MockProxyService_HandleRequest_Call{Call: _e.mock.On("HandleRequest", ctx, req)}
}

func (_c *MockProxyService_HandleRequest_Call) Run(run func(ctx context.Context, req proxy.ProxyRequest)) *MockProxyService_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proxy.ProxyRequest))
	})
	return _c
}

func (_c *MockProxyService_HandleRequest_Call) Return(_a0 *proxy.ProxyResponse, _a1 error) *MockProxyService_HandleRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProxyService_HandleRequest_Call) RunAndReturn(run func(context.Context, proxy.ProxyRequest) (*proxy.ProxyResponse, error)) *MockProxyService_HandleRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRequest provides a mock function with given fields: req
func (_m *MockProxyService) ValidateRequest(req proxy.ProxyRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(proxy.ProxyRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProxyService_ValidateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRequest'
type MockProxyService_ValidateRequest_Call struct {
	*mock.Call
}

// ValidateRequest is a helper method to define mock.On call
//   - req proxy.ProxyRequest
func (_e *MockProxyService_Expecter) ValidateRequest(req interface{}) *MockProxyService_ValidateRequest_Call {
	return &MockProxyService_ValidateRequest_Call{Call: _e.mock.On("ValidateRequest", req)}
}

func (_c *MockProxyService_ValidateRequest_Call) Run(run func(req proxy.ProxyRequest)) *MockProxyService_ValidateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(proxy.ProxyRequest))
	})
	return _c
}

func (_c *MockProxyService_ValidateRequest_Call) Return(_a0 error) *MockProxyService_ValidateRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyService_ValidateRequest_Call) RunAndReturn(run func(proxy.ProxyRequest) error) *MockProxyService_ValidateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProxyService creates a new instance of MockProxyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProxyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProxyService {
	mock := &MockProxyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
