// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	proxy "proxynd/internal/services/proxy"

	mock "github.com/stretchr/testify/mock"
)

// MockUpstreamClient is an autogenerated mock type for the UpstreamClient type
type MockUpstreamClient struct {
	mock.Mock
}

type MockUpstreamClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpstreamClient) EXPECT() *MockUpstreamClient_Expecter {
	return &MockUpstreamClient_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, url, headers
func (_m *MockUpstreamClient) Fetch(ctx context.Context, url string, headers map[string]string) (*proxy.ProxyResponse, error) {
	ret := _m.Called(ctx, url, headers)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *proxy.ProxyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (*proxy.ProxyResponse, error)); ok {
		return rf(ctx, url, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *proxy.ProxyResponse); ok {
		r0 = rf(ctx, url, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ProxyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, url, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpstreamClient_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockUpstreamClient_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers map[string]string
func (_e *MockUpstreamClient_Expecter) Fetch(ctx interface{}, url interface{}, headers interface{}) *MockUpstreamClient_Fetch_Call {
	return &MockUpstreamClient_Fetch_Call{Call: _e.mock.On("Fetch", ctx, url, headers)}
}

func (_c *MockUpstreamClient_Fetch_Call) Run(run func(ctx context.Context, url string, headers map[string]string)) *MockUpstreamClient_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockUpstreamClient_Fetch_Call) Return(_a0 *proxy.ProxyResponse, _a1 error) *MockUpstreamClient_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpstreamClient_Fetch_Call) RunAndReturn(run func(context.Context, string, map[string]string) (*proxy.ProxyResponse, error)) *MockUpstreamClient_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpstreamClient creates a new instance of MockUpstreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpstreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpstreamClient {
	mock := &MockUpstreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
