// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "proxynd/internal/services/proxy"

	mock "github.com/stretchr/testify/mock"
)

// MockUpstreamClient is an autogenerated mock type for the UpstreamClient type
type MockUpstreamClient struct {
	mock.Mock
}

type MockUpstreamClient_Expecter struct {
	mock *MockUpstreamClient
}

func (_m *MockUpstreamClient) EXPECT() *MockUpstreamClient_Expecter {
	return &MockUpstreamClient_Expecter{mock: _m}
}

// Fetch provides a mock function with given fields: ctx, url, headers
func (_m *MockUpstreamClient) Fetch(ctx context.Context, url string, headers map[string]string) (*proxy.ProxyResponse, error) {
	ret := _m.Called(ctx, url, headers)

	var r0 *proxy.ProxyResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *proxy.ProxyResponse); ok {
		r0 = rf(ctx, url, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ProxyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, url, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUpstreamClient creates a new instance of MockUpstreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUpstreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpstreamClient {
	mock := &MockUpstreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
