// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, credentials
func (_m *MockAuthService) Authenticate(ctx context.Context, credentials interfaces.Credentials) (*interfaces.User, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Credentials) (*interfaces.User, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Credentials) *interfaces.User); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Credentials) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials interfaces.Credentials
func (_e *MockAuthService_Expecter) Authenticate(ctx interface{}, credentials interface{}) *MockAuthService_Authenticate_Call {
	return &MockAuthService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, credentials)}
}

func (_c *MockAuthService_Authenticate_Call) Run(run func(ctx context.Context, credentials interfaces.Credentials)) *MockAuthService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Credentials))
	})
	return _c
}

func (_c *MockAuthService_Authenticate_Call) Return(_a0 *interfaces.User, _a1 error) *MockAuthService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Authenticate_Call) RunAndReturn(run func(context.Context, interfaces.Credentials) (*interfaces.User, error)) *MockAuthService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizeRequest provides a mock function with given fields: ctx, token, resource, action
func (_m *MockAuthService) AuthorizeRequest(ctx context.Context, token string, resource string, action string) (bool, error) {
	ret := _m.Called(ctx, token, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeRequest")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, token, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, token, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, token, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_AuthorizeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeRequest'
type MockAuthService_AuthorizeRequest_Call struct {
	*mock.Call
}

// AuthorizeRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - resource string
//   - action string
func (_e *MockAuthService_Expecter) AuthorizeRequest(ctx interface{}, token interface{}, resource interface{}, action interface{}) *MockAuthService_AuthorizeRequest_Call {
	return &MockAuthService_AuthorizeRequest_Call{Call: _e.mock.On("AuthorizeRequest", ctx, token, resource, action)}
}

func (_c *MockAuthService_AuthorizeRequest_Call) Run(run func(ctx context.Context, token string, resource string, action string)) *MockAuthService_AuthorizeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_AuthorizeRequest_Call) Return(_a0 bool, _a1 error) *MockAuthService_AuthorizeRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_AuthorizeRequest_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *MockAuthService_AuthorizeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockAuthService) CreateUser(ctx context.Context, user *interfaces.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *interfaces.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *interfaces.User
func (_e *MockAuthService_Expecter) CreateUser(ctx interface{}, user interface{}) *MockAuthService_CreateUser_Call {
	return &MockAuthService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockAuthService_CreateUser_Call) Run(run func(ctx context.Context, user *interfaces.User)) *MockAuthService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*interfaces.User))
	})
	return _c
}

func (_c *MockAuthService_CreateUser_Call) Return(_a0 error) *MockAuthService_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_CreateUser_Call) RunAndReturn(run func(context.Context, *interfaces.User) error) *MockAuthService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) GetUser(ctx context.Context, userID string) (*interfaces.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*interfaces.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *interfaces.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) GetUser(ctx interface{}, userID interface{}) *MockAuthService_GetUser_Call {
	return &MockAuthService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *MockAuthService_GetUser_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_GetUser_Call) Return(_a0 *interfaces.User, _a1 error) *MockAuthService_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetUser_Call) RunAndReturn(run func(context.Context, string) (*interfaces.User, error)) *MockAuthService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, userID, updates
func (_m *MockAuthService) UpdateUser(ctx context.Context, userID string, updates map[string]interface{}) error {
	ret := _m.Called(ctx, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, userID, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAuthService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - updates map[string]interface{}
func (_e *MockAuthService_Expecter) UpdateUser(ctx interface{}, userID interface{}, updates interface{}) *MockAuthService_UpdateUser_Call {
	return &MockAuthService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, updates)}
}

func (_c *MockAuthService_UpdateUser_Call) Run(run func(ctx context.Context, userID string, updates map[string]interface{})) *MockAuthService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockAuthService_UpdateUser_Call) Return(_a0 error) *MockAuthService_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_UpdateUser_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockAuthService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
