// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCacheManager is an autogenerated mock type for the CacheManager type
type MockCacheManager struct {
	mock.Mock
}

type MockCacheManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheManager) EXPECT() *MockCacheManager_Expecter {
	return &MockCacheManager_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *MockCacheManager) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheManager_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCacheManager_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheManager_Expecter) Clear(ctx interface{}) *MockCacheManager_Clear_Call {
	return &MockCacheManager_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *MockCacheManager_Clear_Call) Run(run func(ctx context.Context)) *MockCacheManager_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCacheManager_Clear_Call) Return(_a0 error) *MockCacheManager_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_Clear_Call) RunAndReturn(run func(context.Context) error) *MockCacheManager_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockCacheManager) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheManager_Expecter) Delete(ctx interface{}, key interface{}) *MockCacheManager_Delete_Call {
	return &MockCacheManager_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCacheManager_Delete_Call) Run(run func(ctx context.Context, key string)) *MockCacheManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheManager_Delete_Call) Return(_a0 error) *MockCacheManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockCacheManager) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheManager_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCacheManager_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheManager_Expecter) Exists(ctx interface{}, key interface{}) *MockCacheManager_Exists_Call {
	return &MockCacheManager_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockCacheManager_Exists_Call) Run(run func(ctx context.Context, key string)) *MockCacheManager_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheManager_Exists_Call) Return(_a0 bool, _a1 error) *MockCacheManager_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheManager_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCacheManager_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockCacheManager) Get(ctx context.Context, key string) ([]byte, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCacheManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheManager_Expecter) Get(ctx interface{}, key interface{}) *MockCacheManager_Get_Call {
	return &MockCacheManager_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheManager_Get_Call) Run(run func(ctx context.Context, key string)) *MockCacheManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheManager_Get_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockCacheManager_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCacheManager_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, bool, error)) *MockCacheManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with no fields
func (_m *MockCacheManager) GetStats() interfaces.CacheStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 interfaces.CacheStats
	if rf, ok := ret.Get(0).(func() interfaces.CacheStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(interfaces.CacheStats)
	}

	return r0
}

// MockCacheManager_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockCacheManager_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockCacheManager_Expecter) GetStats() *MockCacheManager_GetStats_Call {
	return &MockCacheManager_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockCacheManager_GetStats_Call) Run(run func()) *MockCacheManager_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheManager_GetStats_Call) Return(_a0 interfaces.CacheStats) *MockCacheManager_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_GetStats_Call) RunAndReturn(run func() interfaces.CacheStats) *MockCacheManager_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, data, ttl
func (_m *MockCacheManager) Put(ctx context.Context, key string, data []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, key, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, key, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheManager_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockCacheManager_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - ttl time.Duration
func (_e *MockCacheManager_Expecter) Put(ctx interface{}, key interface{}, data interface{}, ttl interface{}) *MockCacheManager_Put_Call {
	return &MockCacheManager_Put_Call{Call: _e.mock.On("Put", ctx, key, data, ttl)}
}

func (_c *MockCacheManager_Put_Call) Run(run func(ctx context.Context, key string, data []byte, ttl time.Duration)) *MockCacheManager_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCacheManager_Put_Call) Return(_a0 error) *MockCacheManager_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_Put_Call) RunAndReturn(run func(context.Context, string, []byte, time.Duration) error) *MockCacheManager_Put_Call {
	_c.Call.Return(run)
	return _c
}

// StartEviction provides a mock function with given fields: ctx, interval
func (_m *MockCacheManager) StartEviction(ctx context.Context, interval time.Duration) {
	_m.Called(ctx, interval)
}

// MockCacheManager_StartEviction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEviction'
type MockCacheManager_StartEviction_Call struct {
	*mock.Call
}

// StartEviction is a helper method to define mock.On call
//   - ctx context.Context
//   - interval time.Duration
func (_e *MockCacheManager_Expecter) StartEviction(ctx interface{}, interval interface{}) *MockCacheManager_StartEviction_Call {
	return &MockCacheManager_StartEviction_Call{Call: _e.mock.On("StartEviction", ctx, interval)}
}

func (_c *MockCacheManager_StartEviction_Call) Run(run func(ctx context.Context, interval time.Duration)) *MockCacheManager_StartEviction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockCacheManager_StartEviction_Call) Return() *MockCacheManager_StartEviction_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheManager_StartEviction_Call) RunAndReturn(run func(context.Context, time.Duration)) *MockCacheManager_StartEviction_Call {
	_c.Run(run)
	return _c
}

// StopEviction provides a mock function with no fields
func (_m *MockCacheManager) StopEviction() {
	_m.Called()
}

// MockCacheManager_StopEviction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopEviction'
type MockCacheManager_StopEviction_Call struct {
	*mock.Call
}

// StopEviction is a helper method to define mock.On call
func (_e *MockCacheManager_Expecter) StopEviction() *MockCacheManager_StopEviction_Call {
	return &MockCacheManager_StopEviction_Call{Call: _e.mock.On("StopEviction")}
}

func (_c *MockCacheManager_StopEviction_Call) Run(run func()) *MockCacheManager_StopEviction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheManager_StopEviction_Call) Return() *MockCacheManager_StopEviction_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheManager_StopEviction_Call) RunAndReturn(run func()) *MockCacheManager_StopEviction_Call {
	_c.Run(run)
	return _c
}

// NewMockCacheManager creates a new instance of MockCacheManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheManager {
	mock := &MockCacheManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
