// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheBackend is an autogenerated mock type for the CacheBackend type
type MockCacheBackend struct {
	mock.Mock
}

type MockCacheBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheBackend) EXPECT() *MockCacheBackend_Expecter {
	return &MockCacheBackend_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with no fields
func (_m *MockCacheBackend) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheBackend_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCacheBackend_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockCacheBackend_Expecter) Clear() *MockCacheBackend_Clear_Call {
	return &MockCacheBackend_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockCacheBackend_Clear_Call) Run(run func()) *MockCacheBackend_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheBackend_Clear_Call) Return(_a0 error) *MockCacheBackend_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheBackend_Clear_Call) RunAndReturn(run func() error) *MockCacheBackend_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: key
func (_m *MockCacheBackend) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *MockCacheBackend_Expecter) Delete(key interface{}) *MockCacheBackend_Delete_Call {
	return &MockCacheBackend_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCacheBackend_Delete_Call) Run(run func(key string)) *MockCacheBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCacheBackend_Delete_Call) Return(_a0 error) *MockCacheBackend_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheBackend_Delete_Call) RunAndReturn(run func(string) error) *MockCacheBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockCacheBackend) Get(key string) ([]byte, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCacheBackend_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheBackend_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockCacheBackend_Expecter) Get(key interface{}) *MockCacheBackend_Get_Call {
	return &MockCacheBackend_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCacheBackend_Get_Call) Run(run func(key string)) *MockCacheBackend_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCacheBackend_Get_Call) Return(_a0 []byte, _a1 bool) *MockCacheBackend_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheBackend_Get_Call) RunAndReturn(run func(string) ([]byte, bool)) *MockCacheBackend_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function with no fields
func (_m *MockCacheBackend) Keys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockCacheBackend_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockCacheBackend_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockCacheBackend_Expecter) Keys() *MockCacheBackend_Keys_Call {
	return &MockCacheBackend_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockCacheBackend_Keys_Call) Run(run func()) *MockCacheBackend_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheBackend_Keys_Call) Return(_a0 []string) *MockCacheBackend_Keys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheBackend_Keys_Call) RunAndReturn(run func() []string) *MockCacheBackend_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value, expiration
func (_m *MockCacheBackend) Set(key string, value []byte, expiration time.Duration) error {
	ret := _m.Called(key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = rf(key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheBackend_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheBackend_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - expiration time.Duration
func (_e *MockCacheBackend_Expecter) Set(key interface{}, value interface{}, expiration interface{}) *MockCacheBackend_Set_Call {
	return &MockCacheBackend_Set_Call{Call: _e.mock.On("Set", key, value, expiration)}
}

func (_c *MockCacheBackend_Set_Call) Run(run func(key string, value []byte, expiration time.Duration)) *MockCacheBackend_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockCacheBackend_Set_Call) Return(_a0 error) *MockCacheBackend_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheBackend_Set_Call) RunAndReturn(run func(string, []byte, time.Duration) error) *MockCacheBackend_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockCacheBackend) Size() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockCacheBackend_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockCacheBackend_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockCacheBackend_Expecter) Size() *MockCacheBackend_Size_Call {
	return &MockCacheBackend_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockCacheBackend_Size_Call) Run(run func()) *MockCacheBackend_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheBackend_Size_Call) Return(_a0 int64) *MockCacheBackend_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheBackend_Size_Call) RunAndReturn(run func() int64) *MockCacheBackend_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheBackend creates a new instance of MockCacheBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheBackend {
	mock := &MockCacheBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
