// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockHealthService is an autogenerated mock type for the HealthService type
type MockHealthService struct {
	mock.Mock
}

type MockHealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthService) EXPECT() *MockHealthService_Expecter {
	return &MockHealthService_Expecter{mock: &_m.Mock}
}

// ForceCheck provides a mock function with given fields: ctx
func (_m *MockHealthService) ForceCheck(ctx context.Context) interfaces.HealthStatus {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ForceCheck")
	}

	var r0 interfaces.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context) interfaces.HealthStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(interfaces.HealthStatus)
	}

	return r0
}

// MockHealthService_ForceCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceCheck'
type MockHealthService_ForceCheck_Call struct {
	*mock.Call
}

// ForceCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthService_Expecter) ForceCheck(ctx interface{}) *MockHealthService_ForceCheck_Call {
	return &MockHealthService_ForceCheck_Call{Call: _e.mock.On("ForceCheck", ctx)}
}

func (_c *MockHealthService_ForceCheck_Call) Run(run func(ctx context.Context)) *MockHealthService_ForceCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthService_ForceCheck_Call) Return(_a0 interfaces.HealthStatus) *MockHealthService_ForceCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthService_ForceCheck_Call) RunAndReturn(run func(context.Context) interfaces.HealthStatus) *MockHealthService_ForceCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailedStatus provides a mock function with no fields
func (_m *MockHealthService) GetDetailedStatus() map[string]interfaces.CheckResult {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedStatus")
	}

	var r0 map[string]interfaces.CheckResult
	if rf, ok := ret.Get(0).(func() map[string]interfaces.CheckResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interfaces.CheckResult)
		}
	}

	return r0
}

// MockHealthService_GetDetailedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailedStatus'
type MockHealthService_GetDetailedStatus_Call struct {
	*mock.Call
}

// GetDetailedStatus is a helper method to define mock.On call
func (_e *MockHealthService_Expecter) GetDetailedStatus() *MockHealthService_GetDetailedStatus_Call {
	return &MockHealthService_GetDetailedStatus_Call{Call: _e.mock.On("GetDetailedStatus")}
}

func (_c *MockHealthService_GetDetailedStatus_Call) Run(run func()) *MockHealthService_GetDetailedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthService_GetDetailedStatus_Call) Return(_a0 map[string]interfaces.CheckResult) *MockHealthService_GetDetailedStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthService_GetDetailedStatus_Call) RunAndReturn(run func() map[string]interfaces.CheckResult) *MockHealthService_GetDetailedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with no fields
func (_m *MockHealthService) GetStatus() interfaces.HealthStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 interfaces.HealthStatus
	if rf, ok := ret.Get(0).(func() interfaces.HealthStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(interfaces.HealthStatus)
	}

	return r0
}

// MockHealthService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockHealthService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockHealthService_Expecter) GetStatus() *MockHealthService_GetStatus_Call {
	return &MockHealthService_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockHealthService_GetStatus_Call) Run(run func()) *MockHealthService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthService_GetStatus_Call) Return(_a0 interfaces.HealthStatus) *MockHealthService_GetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthService_GetStatus_Call) RunAndReturn(run func() interfaces.HealthStatus) *MockHealthService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetUptime provides a mock function with no fields
func (_m *MockHealthService) GetUptime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUptime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockHealthService_GetUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUptime'
type MockHealthService_GetUptime_Call struct {
	*mock.Call
}

// GetUptime is a helper method to define mock.On call
func (_e *MockHealthService_Expecter) GetUptime() *MockHealthService_GetUptime_Call {
	return &MockHealthService_GetUptime_Call{Call: _e.mock.On("GetUptime")}
}

func (_c *MockHealthService_GetUptime_Call) Run(run func()) *MockHealthService_GetUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthService_GetUptime_Call) Return(_a0 time.Duration) *MockHealthService_GetUptime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthService_GetUptime_Call) RunAndReturn(run func() time.Duration) *MockHealthService_GetUptime_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterChecker provides a mock function with given fields: name, checker
func (_m *MockHealthService) RegisterChecker(name string, checker interfaces.HealthChecker) {
	_m.Called(name, checker)
}

// MockHealthService_RegisterChecker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChecker'
type MockHealthService_RegisterChecker_Call struct {
	*mock.Call
}

// RegisterChecker is a helper method to define mock.On call
//   - name string
//   - checker interfaces.HealthChecker
func (_e *MockHealthService_Expecter) RegisterChecker(name interface{}, checker interface{}) *MockHealthService_RegisterChecker_Call {
	return &MockHealthService_RegisterChecker_Call{Call: _e.mock.On("RegisterChecker", name, checker)}
}

func (_c *MockHealthService_RegisterChecker_Call) Run(run func(name string, checker interfaces.HealthChecker)) *MockHealthService_RegisterChecker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interfaces.HealthChecker))
	})
	return _c
}

func (_c *MockHealthService_RegisterChecker_Call) Return() *MockHealthService_RegisterChecker_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthService_RegisterChecker_Call) RunAndReturn(run func(string, interfaces.HealthChecker)) *MockHealthService_RegisterChecker_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockHealthService) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockHealthService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHealthService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthService_Expecter) Start(ctx interface{}) *MockHealthService_Start_Call {
	return &MockHealthService_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockHealthService_Start_Call) Run(run func(ctx context.Context)) *MockHealthService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthService_Start_Call) Return() *MockHealthService_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthService_Start_Call) RunAndReturn(run func(context.Context)) *MockHealthService_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockHealthService) Stop() {
	_m.Called()
}

// MockHealthService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockHealthService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockHealthService_Expecter) Stop() *MockHealthService_Stop_Call {
	return &MockHealthService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockHealthService_Stop_Call) Run(run func()) *MockHealthService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthService_Stop_Call) Return() *MockHealthService_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthService_Stop_Call) RunAndReturn(run func()) *MockHealthService_Stop_Call {
	_c.Run(run)
	return _c
}

// UnregisterChecker provides a mock function with given fields: name
func (_m *MockHealthService) UnregisterChecker(name string) {
	_m.Called(name)
}

// MockHealthService_UnregisterChecker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterChecker'
type MockHealthService_UnregisterChecker_Call struct {
	*mock.Call
}

// UnregisterChecker is a helper method to define mock.On call
//   - name string
func (_e *MockHealthService_Expecter) UnregisterChecker(name interface{}) *MockHealthService_UnregisterChecker_Call {
	return &MockHealthService_UnregisterChecker_Call{Call: _e.mock.On("UnregisterChecker", name)}
}

func (_c *MockHealthService_UnregisterChecker_Call) Run(run func(name string)) *MockHealthService_UnregisterChecker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthService_UnregisterChecker_Call) Return() *MockHealthService_UnregisterChecker_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthService_UnregisterChecker_Call) RunAndReturn(run func(string)) *MockHealthService_UnregisterChecker_Call {
	_c.Run(run)
	return _c
}

// NewMockHealthService creates a new instance of MockHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthService {
	mock := &MockHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
