// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// ExtractClaims provides a mock function with given fields: tokenString
func (_m *MockJWTService) ExtractClaims(tokenString string) (*interfaces.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ExtractClaims")
	}

	var r0 *interfaces.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*interfaces.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *interfaces.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ExtractClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractClaims'
type MockJWTService_ExtractClaims_Call struct {
	*mock.Call
}

// ExtractClaims is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) ExtractClaims(tokenString interface{}) *MockJWTService_ExtractClaims_Call {
	return &MockJWTService_ExtractClaims_Call{Call: _e.mock.On("ExtractClaims", tokenString)}
}

func (_c *MockJWTService_ExtractClaims_Call) Run(run func(tokenString string)) *MockJWTService_ExtractClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_ExtractClaims_Call) Return(_a0 *interfaces.Claims, _a1 error) *MockJWTService_ExtractClaims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ExtractClaims_Call) RunAndReturn(run func(string) (*interfaces.Claims, error)) *MockJWTService_ExtractClaims_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenPair provides a mock function with given fields: userID, email, name, username, role, provider, organizations
func (_m *MockJWTService) GenerateTokenPair(userID string, email string, name string, username string, role string, provider string, organizations []string) (*interfaces.TokenPair, error) {
	ret := _m.Called(userID, email, name, username, role, provider, organizations)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *interfaces.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, []string) (*interfaces.TokenPair, error)); ok {
		return rf(userID, email, name, username, role, provider, organizations)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, []string) *interfaces.TokenPair); ok {
		r0 = rf(userID, email, name, username, role, provider, organizations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string, []string) error); ok {
		r1 = rf(userID, email, name, username, role, provider, organizations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockJWTService_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - userID string
//   - email string
//   - name string
//   - username string
//   - role string
//   - provider string
//   - organizations []string
func (_e *MockJWTService_Expecter) GenerateTokenPair(userID interface{}, email interface{}, name interface{}, username interface{}, role interface{}, provider interface{}, organizations interface{}) *MockJWTService_GenerateTokenPair_Call {
	return &MockJWTService_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", userID, email, name, username, role, provider, organizations)}
}

func (_c *MockJWTService_GenerateTokenPair_Call) Run(run func(userID string, email string, name string, username string, role string, provider string, organizations []string)) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].([]string))
	})
	return _c
}

func (_c *MockJWTService_GenerateTokenPair_Call) Return(_a0 *interfaces.TokenPair, _a1 error) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_GenerateTokenPair_Call) RunAndReturn(run func(string, string, string, string, string, string, []string) (*interfaces.TokenPair, error)) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function with given fields: refreshTokenString
func (_m *MockJWTService) RefreshAccessToken(refreshTokenString string) (*interfaces.TokenPair, error) {
	ret := _m.Called(refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *interfaces.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*interfaces.TokenPair, error)); ok {
		return rf(refreshTokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *interfaces.TokenPair); ok {
		r0 = rf(refreshTokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshTokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockJWTService_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - refreshTokenString string
func (_e *MockJWTService_Expecter) RefreshAccessToken(refreshTokenString interface{}) *MockJWTService_RefreshAccessToken_Call {
	return &MockJWTService_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", refreshTokenString)}
}

func (_c *MockJWTService_RefreshAccessToken_Call) Run(run func(refreshTokenString string)) *MockJWTService_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_RefreshAccessToken_Call) Return(_a0 *interfaces.TokenPair, _a1 error) *MockJWTService_RefreshAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_RefreshAccessToken_Call) RunAndReturn(run func(string) (*interfaces.TokenPair, error)) *MockJWTService_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: tokenString
func (_m *MockJWTService) RevokeToken(tokenString string) error {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJWTService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockJWTService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) RevokeToken(tokenString interface{}) *MockJWTService_RevokeToken_Call {
	return &MockJWTService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", tokenString)}
}

func (_c *MockJWTService_RevokeToken_Call) Run(run func(tokenString string)) *MockJWTService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_RevokeToken_Call) Return(_a0 error) *MockJWTService_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJWTService_RevokeToken_Call) RunAndReturn(run func(string) error) *MockJWTService_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: tokenString
func (_m *MockJWTService) ValidateAccessToken(tokenString string) (*interfaces.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *interfaces.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*interfaces.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *interfaces.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockJWTService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) ValidateAccessToken(tokenString interface{}) *MockJWTService_ValidateAccessToken_Call {
	return &MockJWTService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenString)}
}

func (_c *MockJWTService_ValidateAccessToken_Call) Run(run func(tokenString string)) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_ValidateAccessToken_Call) Return(_a0 *interfaces.Claims, _a1 error) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ValidateAccessToken_Call) RunAndReturn(run func(string) (*interfaces.Claims, error)) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *MockJWTService) ValidateToken(tokenString string) (*interfaces.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *interfaces.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*interfaces.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *interfaces.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockJWTService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) ValidateToken(tokenString interface{}) *MockJWTService_ValidateToken_Call {
	return &MockJWTService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockJWTService_ValidateToken_Call) Run(run func(tokenString string)) *MockJWTService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_ValidateToken_Call) Return(_a0 *interfaces.Claims, _a1 error) *MockJWTService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ValidateToken_Call) RunAndReturn(run func(string) (*interfaces.Claims, error)) *MockJWTService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
