// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockPackageVerifier is an autogenerated mock type for the PackageVerifier type
type MockPackageVerifier struct {
	mock.Mock
}

type MockPackageVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageVerifier) EXPECT() *MockPackageVerifier_Expecter {
	return &MockPackageVerifier_Expecter{mock: &_m.Mock}
}

// GetSupportedTypes provides a mock function with no fields
func (_m *MockPackageVerifier) GetSupportedTypes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedTypes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockPackageVerifier_GetSupportedTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedTypes'
type MockPackageVerifier_GetSupportedTypes_Call struct {
	*mock.Call
}

// GetSupportedTypes is a helper method to define mock.On call
func (_e *MockPackageVerifier_Expecter) GetSupportedTypes() *MockPackageVerifier_GetSupportedTypes_Call {
	return &MockPackageVerifier_GetSupportedTypes_Call{Call: _e.mock.On("GetSupportedTypes")}
}

func (_c *MockPackageVerifier_GetSupportedTypes_Call) Run(run func()) *MockPackageVerifier_GetSupportedTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageVerifier_GetSupportedTypes_Call) Return(_a0 []string) *MockPackageVerifier_GetSupportedTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackageVerifier_GetSupportedTypes_Call) RunAndReturn(run func() []string) *MockPackageVerifier_GetSupportedTypes_Call {
	_c.Call.Return(run)
	return _c
}

// IsStrictMode provides a mock function with no fields
func (_m *MockPackageVerifier) IsStrictMode() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStrictMode")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPackageVerifier_IsStrictMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStrictMode'
type MockPackageVerifier_IsStrictMode_Call struct {
	*mock.Call
}

// IsStrictMode is a helper method to define mock.On call
func (_e *MockPackageVerifier_Expecter) IsStrictMode() *MockPackageVerifier_IsStrictMode_Call {
	return &MockPackageVerifier_IsStrictMode_Call{Call: _e.mock.On("IsStrictMode")}
}

func (_c *MockPackageVerifier_IsStrictMode_Call) Run(run func()) *MockPackageVerifier_IsStrictMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageVerifier_IsStrictMode_Call) Return(_a0 bool) *MockPackageVerifier_IsStrictMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackageVerifier_IsStrictMode_Call) RunAndReturn(run func() bool) *MockPackageVerifier_IsStrictMode_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterVerifier provides a mock function with given fields: packageType, verifier
func (_m *MockPackageVerifier) RegisterVerifier(packageType string, verifier interfaces.TypedPackageVerifier) error {
	ret := _m.Called(packageType, verifier)

	if len(ret) == 0 {
		panic("no return value specified for RegisterVerifier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interfaces.TypedPackageVerifier) error); ok {
		r0 = rf(packageType, verifier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPackageVerifier_RegisterVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterVerifier'
type MockPackageVerifier_RegisterVerifier_Call struct {
	*mock.Call
}

// RegisterVerifier is a helper method to define mock.On call
//   - packageType string
//   - verifier interfaces.TypedPackageVerifier
func (_e *MockPackageVerifier_Expecter) RegisterVerifier(packageType interface{}, verifier interface{}) *MockPackageVerifier_RegisterVerifier_Call {
	return &MockPackageVerifier_RegisterVerifier_Call{Call: _e.mock.On("RegisterVerifier", packageType, verifier)}
}

func (_c *MockPackageVerifier_RegisterVerifier_Call) Run(run func(packageType string, verifier interfaces.TypedPackageVerifier)) *MockPackageVerifier_RegisterVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interfaces.TypedPackageVerifier))
	})
	return _c
}

func (_c *MockPackageVerifier_RegisterVerifier_Call) Return(_a0 error) *MockPackageVerifier_RegisterVerifier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackageVerifier_RegisterVerifier_Call) RunAndReturn(run func(string, interfaces.TypedPackageVerifier) error) *MockPackageVerifier_RegisterVerifier_Call {
	_c.Call.Return(run)
	return _c
}

// SetStrictMode provides a mock function with given fields: strict
func (_m *MockPackageVerifier) SetStrictMode(strict bool) {
	_m.Called(strict)
}

// MockPackageVerifier_SetStrictMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStrictMode'
type MockPackageVerifier_SetStrictMode_Call struct {
	*mock.Call
}

// SetStrictMode is a helper method to define mock.On call
//   - strict bool
func (_e *MockPackageVerifier_Expecter) SetStrictMode(strict interface{}) *MockPackageVerifier_SetStrictMode_Call {
	return &MockPackageVerifier_SetStrictMode_Call{Call: _e.mock.On("SetStrictMode", strict)}
}

func (_c *MockPackageVerifier_SetStrictMode_Call) Run(run func(strict bool)) *MockPackageVerifier_SetStrictMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockPackageVerifier_SetStrictMode_Call) Return() *MockPackageVerifier_SetStrictMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPackageVerifier_SetStrictMode_Call) RunAndReturn(run func(bool)) *MockPackageVerifier_SetStrictMode_Call {
	_c.Run(run)
	return _c
}

// VerifyPackage provides a mock function with given fields: ctx, packageType, packagePath, data, metadata
func (_m *MockPackageVerifier) VerifyPackage(ctx context.Context, packageType string, packagePath string, data []byte, metadata map[string]string) (*interfaces.VerificationResult, error) {
	ret := _m.Called(ctx, packageType, packagePath, data, metadata)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPackage")
	}

	var r0 *interfaces.VerificationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) (*interfaces.VerificationResult, error)); ok {
		return rf(ctx, packageType, packagePath, data, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) *interfaces.VerificationResult); ok {
		r0 = rf(ctx, packageType, packagePath, data, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.VerificationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte, map[string]string) error); ok {
		r1 = rf(ctx, packageType, packagePath, data, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageVerifier_VerifyPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPackage'
type MockPackageVerifier_VerifyPackage_Call struct {
	*mock.Call
}

// VerifyPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - packageType string
//   - packagePath string
//   - data []byte
//   - metadata map[string]string
func (_e *MockPackageVerifier_Expecter) VerifyPackage(ctx interface{}, packageType interface{}, packagePath interface{}, data interface{}, metadata interface{}) *MockPackageVerifier_VerifyPackage_Call {
	return &MockPackageVerifier_VerifyPackage_Call{Call: _e.mock.On("VerifyPackage", ctx, packageType, packagePath, data, metadata)}
}

func (_c *MockPackageVerifier_VerifyPackage_Call) Run(run func(ctx context.Context, packageType string, packagePath string, data []byte, metadata map[string]string)) *MockPackageVerifier_VerifyPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockPackageVerifier_VerifyPackage_Call) Return(_a0 *interfaces.VerificationResult, _a1 error) *MockPackageVerifier_VerifyPackage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageVerifier_VerifyPackage_Call) RunAndReturn(run func(context.Context, string, string, []byte, map[string]string) (*interfaces.VerificationResult, error)) *MockPackageVerifier_VerifyPackage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackageVerifier creates a new instance of MockPackageVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageVerifier {
	mock := &MockPackageVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
