// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockTypedPackageVerifier is an autogenerated mock type for the TypedPackageVerifier type
type MockTypedPackageVerifier struct {
	mock.Mock
}

type MockTypedPackageVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTypedPackageVerifier) EXPECT() *MockTypedPackageVerifier_Expecter {
	return &MockTypedPackageVerifier_Expecter{mock: &_m.Mock}
}

// Type provides a mock function with no fields
func (_m *MockTypedPackageVerifier) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTypedPackageVerifier_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockTypedPackageVerifier_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockTypedPackageVerifier_Expecter) Type() *MockTypedPackageVerifier_Type_Call {
	return &MockTypedPackageVerifier_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockTypedPackageVerifier_Type_Call) Run(run func()) *MockTypedPackageVerifier_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTypedPackageVerifier_Type_Call) Return(_a0 string) *MockTypedPackageVerifier_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTypedPackageVerifier_Type_Call) RunAndReturn(run func() string) *MockTypedPackageVerifier_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, packagePath, data, metadata
func (_m *MockTypedPackageVerifier) Verify(ctx context.Context, packagePath string, data []byte, metadata map[string]string) (*interfaces.VerificationResult, error) {
	ret := _m.Called(ctx, packagePath, data, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *interfaces.VerificationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) (*interfaces.VerificationResult, error)); ok {
		return rf(ctx, packagePath, data, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) *interfaces.VerificationResult); ok {
		r0 = rf(ctx, packagePath, data, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.VerificationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, map[string]string) error); ok {
		r1 = rf(ctx, packagePath, data, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTypedPackageVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTypedPackageVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - packagePath string
//   - data []byte
//   - metadata map[string]string
func (_e *MockTypedPackageVerifier_Expecter) Verify(ctx interface{}, packagePath interface{}, data interface{}, metadata interface{}) *MockTypedPackageVerifier_Verify_Call {
	return &MockTypedPackageVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, packagePath, data, metadata)}
}

func (_c *MockTypedPackageVerifier_Verify_Call) Run(run func(ctx context.Context, packagePath string, data []byte, metadata map[string]string)) *MockTypedPackageVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockTypedPackageVerifier_Verify_Call) Return(_a0 *interfaces.VerificationResult, _a1 error) *MockTypedPackageVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTypedPackageVerifier_Verify_Call) RunAndReturn(run func(context.Context, string, []byte, map[string]string) (*interfaces.VerificationResult, error)) *MockTypedPackageVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTypedPackageVerifier creates a new instance of MockTypedPackageVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTypedPackageVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTypedPackageVerifier {
	mock := &MockTypedPackageVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
