// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	alerts "proxynd/alerts"

	context "context"

	"proxynd/internal/config"
	interfaces "proxynd/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockWebhookBatchManager is an autogenerated mock type for the WebhookBatchManager type
type MockWebhookBatchManager struct {
	mock.Mock
}

type MockWebhookBatchManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookBatchManager) EXPECT() *MockWebhookBatchManager_Expecter {
	return &MockWebhookBatchManager_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function with given fields: event, endpoint
func (_m *MockWebhookBatchManager) AddEvent(event *alerts.AlertEvent, endpoint config.WebhookEndpointConfig) {
	_m.Called(event, endpoint)
}

// MockWebhookBatchManager_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type MockWebhookBatchManager_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - event *alerts.AlertEvent
//   - endpoint config.WebhookEndpointConfig
func (_e *MockWebhookBatchManager_Expecter) AddEvent(event interface{}, endpoint interface{}) *MockWebhookBatchManager_AddEvent_Call {
	return &MockWebhookBatchManager_AddEvent_Call{Call: _e.mock.On("AddEvent", event, endpoint)}
}

func (_c *MockWebhookBatchManager_AddEvent_Call) Run(run func(event *alerts.AlertEvent, endpoint config.WebhookEndpointConfig)) *MockWebhookBatchManager_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*alerts.AlertEvent), args[1].(config.WebhookEndpointConfig))
	})
	return _c
}

func (_c *MockWebhookBatchManager_AddEvent_Call) Return() *MockWebhookBatchManager_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebhookBatchManager_AddEvent_Call) RunAndReturn(run func(*alerts.AlertEvent, config.WebhookEndpointConfig)) *MockWebhookBatchManager_AddEvent_Call {
	_c.Run(run)
	return _c
}

// GetStats provides a mock function with no fields
func (_m *MockWebhookBatchManager) GetStats() interfaces.WebhookBatchStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 interfaces.WebhookBatchStats
	if rf, ok := ret.Get(0).(func() interfaces.WebhookBatchStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(interfaces.WebhookBatchStats)
	}

	return r0
}

// MockWebhookBatchManager_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockWebhookBatchManager_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockWebhookBatchManager_Expecter) GetStats() *MockWebhookBatchManager_GetStats_Call {
	return &MockWebhookBatchManager_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockWebhookBatchManager_GetStats_Call) Run(run func()) *MockWebhookBatchManager_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookBatchManager_GetStats_Call) Return(_a0 interfaces.WebhookBatchStats) *MockWebhookBatchManager_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookBatchManager_GetStats_Call) RunAndReturn(run func() interfaces.WebhookBatchStats) *MockWebhookBatchManager_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockWebhookBatchManager) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockWebhookBatchManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWebhookBatchManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebhookBatchManager_Expecter) Start(ctx interface{}) *MockWebhookBatchManager_Start_Call {
	return &MockWebhookBatchManager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockWebhookBatchManager_Start_Call) Run(run func(ctx context.Context)) *MockWebhookBatchManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebhookBatchManager_Start_Call) Return() *MockWebhookBatchManager_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebhookBatchManager_Start_Call) RunAndReturn(run func(context.Context)) *MockWebhookBatchManager_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *MockWebhookBatchManager) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookBatchManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockWebhookBatchManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebhookBatchManager_Expecter) Stop(ctx interface{}) *MockWebhookBatchManager_Stop_Call {
	return &MockWebhookBatchManager_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockWebhookBatchManager_Stop_Call) Run(run func(ctx context.Context)) *MockWebhookBatchManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebhookBatchManager_Stop_Call) Return(_a0 error) *MockWebhookBatchManager_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookBatchManager_Stop_Call) RunAndReturn(run func(context.Context) error) *MockWebhookBatchManager_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookBatchManager creates a new instance of MockWebhookBatchManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookBatchManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookBatchManager {
	mock := &MockWebhookBatchManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
