// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWebhookSender is an autogenerated mock type for the WebhookSender type
type MockWebhookSender struct {
	mock.Mock
}

type MockWebhookSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookSender) EXPECT() *MockWebhookSender_Expecter {
	return &MockWebhookSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, endpoint, payload
func (_m *MockWebhookSender) Send(ctx context.Context, endpoint string, payload interface{}) error {
	ret := _m.Called(ctx, endpoint, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, endpoint, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockWebhookSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
//   - payload interface{}
func (_e *MockWebhookSender_Expecter) Send(ctx interface{}, endpoint interface{}, payload interface{}) *MockWebhookSender_Send_Call {
	return &MockWebhookSender_Send_Call{Call: _e.mock.On("Send", ctx, endpoint, payload)}
}

func (_c *MockWebhookSender_Send_Call) Run(run func(ctx context.Context, endpoint string, payload interface{})) *MockWebhookSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockWebhookSender_Send_Call) Return(_a0 error) *MockWebhookSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookSender_Send_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockWebhookSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function with given fields: ctx, endpoint, payloads
func (_m *MockWebhookSender) SendBatch(ctx context.Context, endpoint string, payloads []interface{}) error {
	ret := _m.Called(ctx, endpoint, payloads)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) error); ok {
		r0 = rf(ctx, endpoint, payloads)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookSender_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockWebhookSender_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
//   - payloads []interface{}
func (_e *MockWebhookSender_Expecter) SendBatch(ctx interface{}, endpoint interface{}, payloads interface{}) *MockWebhookSender_SendBatch_Call {
	return &MockWebhookSender_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, endpoint, payloads)}
}

func (_c *MockWebhookSender_SendBatch_Call) Run(run func(ctx context.Context, endpoint string, payloads []interface{})) *MockWebhookSender_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *MockWebhookSender_SendBatch_Call) Return(_a0 error) *MockWebhookSender_SendBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookSender_SendBatch_Call) RunAndReturn(run func(context.Context, string, []interface{}) error) *MockWebhookSender_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookSender creates a new instance of MockWebhookSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookSender {
	mock := &MockWebhookSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
