// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	yum "proxynd/internal/domain/yum"
)

// MockRepositoryService is an autogenerated mock type for the RepositoryService type
type MockRepositoryService struct {
	mock.Mock
}

type MockRepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryService) EXPECT() *MockRepositoryService_Expecter {
	return &MockRepositoryService_Expecter{mock: &_m.Mock}
}

// GetPackage provides a mock function with given fields: ctx, name, version, arch
func (_m *MockRepositoryService) GetPackage(ctx context.Context, name string, version string, arch string) (*yum.Package, error) {
	ret := _m.Called(ctx, name, version, arch)

	if len(ret) == 0 {
		panic("no return value specified for GetPackage")
	}

	var r0 *yum.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*yum.Package, error)); ok {
		return rf(ctx, name, version, arch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *yum.Package); ok {
		r0 = rf(ctx, name, version, arch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*yum.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, version, arch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryService_GetPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackage'
type MockRepositoryService_GetPackage_Call struct {
	*mock.Call
}

// GetPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - arch string
func (_e *MockRepositoryService_Expecter) GetPackage(ctx interface{}, name interface{}, version interface{}, arch interface{}) *MockRepositoryService_GetPackage_Call {
	return &MockRepositoryService_GetPackage_Call{Call: _e.mock.On("GetPackage", ctx, name, version, arch)}
}

func (_c *MockRepositoryService_GetPackage_Call) Run(run func(ctx context.Context, name string, version string, arch string)) *MockRepositoryService_GetPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepositoryService_GetPackage_Call) Return(_a0 *yum.Package, _a1 error) *MockRepositoryService_GetPackage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryService_GetPackage_Call) RunAndReturn(run func(context.Context, string, string, string) (*yum.Package, error)) *MockRepositoryService_GetPackage_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepositoryMetadata provides a mock function with given fields: ctx, repoId
func (_m *MockRepositoryService) GetRepositoryMetadata(ctx context.Context, repoId string) (*yum.RepositoryMetadata, error) {
	ret := _m.Called(ctx, repoId)

	if len(ret) == 0 {
		panic("no return value specified for GetRepositoryMetadata")
	}

	var r0 *yum.RepositoryMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*yum.RepositoryMetadata, error)); ok {
		return rf(ctx, repoId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *yum.RepositoryMetadata); ok {
		r0 = rf(ctx, repoId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*yum.RepositoryMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryService_GetRepositoryMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepositoryMetadata'
type MockRepositoryService_GetRepositoryMetadata_Call struct {
	*mock.Call
}

// GetRepositoryMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - repoId string
func (_e *MockRepositoryService_Expecter) GetRepositoryMetadata(ctx interface{}, repoId interface{}) *MockRepositoryService_GetRepositoryMetadata_Call {
	return &MockRepositoryService_GetRepositoryMetadata_Call{Call: _e.mock.On("GetRepositoryMetadata", ctx, repoId)}
}

func (_c *MockRepositoryService_GetRepositoryMetadata_Call) Run(run func(ctx context.Context, repoId string)) *MockRepositoryService_GetRepositoryMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryService_GetRepositoryMetadata_Call) Return(_a0 *yum.RepositoryMetadata, _a1 error) *MockRepositoryService_GetRepositoryMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryService_GetRepositoryMetadata_Call) RunAndReturn(run func(context.Context, string) (*yum.RepositoryMetadata, error)) *MockRepositoryService_GetRepositoryMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPackages provides a mock function with given fields: ctx, query, filters
func (_m *MockRepositoryService) SearchPackages(ctx context.Context, query string, filters yum.SearchFilters) ([]yum.Package, error) {
	ret := _m.Called(ctx, query, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchPackages")
	}

	var r0 []yum.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, yum.SearchFilters) ([]yum.Package, error)); ok {
		return rf(ctx, query, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, yum.SearchFilters) []yum.Package); ok {
		r0 = rf(ctx, query, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]yum.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, yum.SearchFilters) error); ok {
		r1 = rf(ctx, query, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryService_SearchPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPackages'
type MockRepositoryService_SearchPackages_Call struct {
	*mock.Call
}

// SearchPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters yum.SearchFilters
func (_e *MockRepositoryService_Expecter) SearchPackages(ctx interface{}, query interface{}, filters interface{}) *MockRepositoryService_SearchPackages_Call {
	return &MockRepositoryService_SearchPackages_Call{Call: _e.mock.On("SearchPackages", ctx, query, filters)}
}

func (_c *MockRepositoryService_SearchPackages_Call) Run(run func(ctx context.Context, query string, filters yum.SearchFilters)) *MockRepositoryService_SearchPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(yum.SearchFilters))
	})
	return _c
}

func (_c *MockRepositoryService_SearchPackages_Call) Return(_a0 []yum.Package, _a1 error) *MockRepositoryService_SearchPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryService_SearchPackages_Call) RunAndReturn(run func(context.Context, string, yum.SearchFilters) ([]yum.Package, error)) *MockRepositoryService_SearchPackages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepository provides a mock function with given fields: ctx, repoId
func (_m *MockRepositoryService) UpdateRepository(ctx context.Context, repoId string) error {
	ret := _m.Called(ctx, repoId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepository")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, repoId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryService_UpdateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepository'
type MockRepositoryService_UpdateRepository_Call struct {
	*mock.Call
}

// UpdateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repoId string
func (_e *MockRepositoryService_Expecter) UpdateRepository(ctx interface{}, repoId interface{}) *MockRepositoryService_UpdateRepository_Call {
	return &MockRepositoryService_UpdateRepository_Call{Call: _e.mock.On("UpdateRepository", ctx, repoId)}
}

func (_c *MockRepositoryService_UpdateRepository_Call) Run(run func(ctx context.Context, repoId string)) *MockRepositoryService_UpdateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryService_UpdateRepository_Call) Return(_a0 error) *MockRepositoryService_UpdateRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryService_UpdateRepository_Call) RunAndReturn(run func(context.Context, string) error) *MockRepositoryService_UpdateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryService creates a new instance of MockRepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryService {
	mock := &MockRepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
