// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetConfigPath provides a mock function with no fields
func (_m *MockRepository) GetConfigPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRepository_GetConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigPath'
type MockRepository_GetConfigPath_Call struct {
	*mock.Call
}

// GetConfigPath is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetConfigPath() *MockRepository_GetConfigPath_Call {
	return &MockRepository_GetConfigPath_Call{Call: _e.mock.On("GetConfigPath")}
}

func (_c *MockRepository_GetConfigPath_Call) Run(run func()) *MockRepository_GetConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetConfigPath_Call) Return(_a0 string) *MockRepository_GetConfigPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_GetConfigPath_Call) RunAndReturn(run func() string) *MockRepository_GetConfigPath_Call {
	_c.Call.Return(run)
	return _c
}

// ListProxyTypes provides a mock function with given fields: ctx
func (_m *MockRepository) ListProxyTypes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProxyTypes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListProxyTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProxyTypes'
type MockRepository_ListProxyTypes_Call struct {
	*mock.Call
}

// ListProxyTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListProxyTypes(ctx interface{}) *MockRepository_ListProxyTypes_Call {
	return &MockRepository_ListProxyTypes_Call{Call: _e.mock.On("ListProxyTypes", ctx)}
}

func (_c *MockRepository_ListProxyTypes_Call) Run(run func(ctx context.Context)) *MockRepository_ListProxyTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListProxyTypes_Call) Return(_a0 []string, _a1 error) *MockRepository_ListProxyTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListProxyTypes_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockRepository_ListProxyTypes_Call {
	_c.Call.Return(run)
	return _c
}

// LoadGlobalConfig provides a mock function with given fields: ctx
func (_m *MockRepository) LoadGlobalConfig(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadGlobalConfig")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_LoadGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadGlobalConfig'
type MockRepository_LoadGlobalConfig_Call struct {
	*mock.Call
}

// LoadGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) LoadGlobalConfig(ctx interface{}) *MockRepository_LoadGlobalConfig_Call {
	return &MockRepository_LoadGlobalConfig_Call{Call: _e.mock.On("LoadGlobalConfig", ctx)}
}

func (_c *MockRepository_LoadGlobalConfig_Call) Run(run func(ctx context.Context)) *MockRepository_LoadGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_LoadGlobalConfig_Call) Return(_a0 interface{}, _a1 error) *MockRepository_LoadGlobalConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_LoadGlobalConfig_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *MockRepository_LoadGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProxyConfig provides a mock function with given fields: ctx, proxyType
func (_m *MockRepository) LoadProxyConfig(ctx context.Context, proxyType string) (interface{}, error) {
	ret := _m.Called(ctx, proxyType)

	if len(ret) == 0 {
		panic("no return value specified for LoadProxyConfig")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, proxyType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, proxyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, proxyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_LoadProxyConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProxyConfig'
type MockRepository_LoadProxyConfig_Call struct {
	*mock.Call
}

// LoadProxyConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - proxyType string
func (_e *MockRepository_Expecter) LoadProxyConfig(ctx interface{}, proxyType interface{}) *MockRepository_LoadProxyConfig_Call {
	return &MockRepository_LoadProxyConfig_Call{Call: _e.mock.On("LoadProxyConfig", ctx, proxyType)}
}

func (_c *MockRepository_LoadProxyConfig_Call) Run(run func(ctx context.Context, proxyType string)) *MockRepository_LoadProxyConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_LoadProxyConfig_Call) Return(_a0 interface{}, _a1 error) *MockRepository_LoadProxyConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_LoadProxyConfig_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockRepository_LoadProxyConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGlobalConfig provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) SaveGlobalConfig(ctx context.Context, _a1 interface{}) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveGlobalConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SaveGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGlobalConfig'
type MockRepository_SaveGlobalConfig_Call struct {
	*mock.Call
}

// SaveGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 interface{}
func (_e *MockRepository_Expecter) SaveGlobalConfig(ctx interface{}, _a1 interface{}) *MockRepository_SaveGlobalConfig_Call {
	return &MockRepository_SaveGlobalConfig_Call{Call: _e.mock.On("SaveGlobalConfig", ctx, _a1)}
}

func (_c *MockRepository_SaveGlobalConfig_Call) Run(run func(ctx context.Context, _a1 interface{})) *MockRepository_SaveGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockRepository_SaveGlobalConfig_Call) Return(_a0 error) *MockRepository_SaveGlobalConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SaveGlobalConfig_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockRepository_SaveGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProxyConfig provides a mock function with given fields: ctx, proxyType, _a2
func (_m *MockRepository) SaveProxyConfig(ctx context.Context, proxyType string, _a2 interface{}) error {
	ret := _m.Called(ctx, proxyType, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveProxyConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, proxyType, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SaveProxyConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProxyConfig'
type MockRepository_SaveProxyConfig_Call struct {
	*mock.Call
}

// SaveProxyConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - proxyType string
//   - _a2 interface{}
func (_e *MockRepository_Expecter) SaveProxyConfig(ctx interface{}, proxyType interface{}, _a2 interface{}) *MockRepository_SaveProxyConfig_Call {
	return &MockRepository_SaveProxyConfig_Call{Call: _e.mock.On("SaveProxyConfig", ctx, proxyType, _a2)}
}

func (_c *MockRepository_SaveProxyConfig_Call) Run(run func(ctx context.Context, proxyType string, _a2 interface{})) *MockRepository_SaveProxyConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRepository_SaveProxyConfig_Call) Return(_a0 error) *MockRepository_SaveProxyConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SaveProxyConfig_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockRepository_SaveProxyConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfig provides a mock function with given fields: ctx, proxyType, _a2
func (_m *MockRepository) ValidateConfig(ctx context.Context, proxyType string, _a2 interface{}) error {
	ret := _m.Called(ctx, proxyType, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, proxyType, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ValidateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfig'
type MockRepository_ValidateConfig_Call struct {
	*mock.Call
}

// ValidateConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - proxyType string
//   - _a2 interface{}
func (_e *MockRepository_Expecter) ValidateConfig(ctx interface{}, proxyType interface{}, _a2 interface{}) *MockRepository_ValidateConfig_Call {
	return &MockRepository_ValidateConfig_Call{Call: _e.mock.On("ValidateConfig", ctx, proxyType, _a2)}
}

func (_c *MockRepository_ValidateConfig_Call) Run(run func(ctx context.Context, proxyType string, _a2 interface{})) *MockRepository_ValidateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRepository_ValidateConfig_Call) Return(_a0 error) *MockRepository_ValidateConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ValidateConfig_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockRepository_ValidateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WatchConfig provides a mock function with given fields: ctx, callback
func (_m *MockRepository) WatchConfig(ctx context.Context, callback func(string, interface{})) error {
	ret := _m.Called(ctx, callback)

	if len(ret) == 0 {
		panic("no return value specified for WatchConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(string, interface{})) error); ok {
		r0 = rf(ctx, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_WatchConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchConfig'
type MockRepository_WatchConfig_Call struct {
	*mock.Call
}

// WatchConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - callback func(string , interface{})
func (_e *MockRepository_Expecter) WatchConfig(ctx interface{}, callback interface{}) *MockRepository_WatchConfig_Call {
	return &MockRepository_WatchConfig_Call{Call: _e.mock.On("WatchConfig", ctx, callback)}
}

func (_c *MockRepository_WatchConfig_Call) Run(run func(ctx context.Context, callback func(string, interface{}))) *MockRepository_WatchConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(string, interface{})))
	})
	return _c
}

func (_c *MockRepository_WatchConfig_Call) Return(_a0 error) *MockRepository_WatchConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_WatchConfig_Call) RunAndReturn(run func(context.Context, func(string, interface{})) error) *MockRepository_WatchConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
