// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	apk "proxynd/internal/domain/apk"
)

// MockPackageService is an autogenerated mock type for the PackageService type
type MockPackageService struct {
	mock.Mock
}

type MockPackageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageService) EXPECT() *MockPackageService_Expecter {
	return &MockPackageService_Expecter{mock: &_m.Mock}
}

// GetPackage provides a mock function with given fields: ctx, name, version, arch
func (_m *MockPackageService) GetPackage(ctx context.Context, name string, version string, arch string) (*apk.Package, error) {
	ret := _m.Called(ctx, name, version, arch)

	if len(ret) == 0 {
		panic("no return value specified for GetPackage")
	}

	var r0 *apk.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*apk.Package, error)); ok {
		return rf(ctx, name, version, arch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *apk.Package); ok {
		r0 = rf(ctx, name, version, arch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apk.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, version, arch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_GetPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackage'
type MockPackageService_GetPackage_Call struct {
	*mock.Call
}

// GetPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - arch string
func (_e *MockPackageService_Expecter) GetPackage(ctx interface{}, name interface{}, version interface{}, arch interface{}) *MockPackageService_GetPackage_Call {
	return &MockPackageService_GetPackage_Call{Call: _e.mock.On("GetPackage", ctx, name, version, arch)}
}

func (_c *MockPackageService_GetPackage_Call) Run(run func(ctx context.Context, name string, version string, arch string)) *MockPackageService_GetPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPackageService_GetPackage_Call) Return(_a0 *apk.Package, _a1 error) *MockPackageService_GetPackage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_GetPackage_Call) RunAndReturn(run func(context.Context, string, string, string) (*apk.Package, error)) *MockPackageService_GetPackage_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepositoryIndex provides a mock function with given fields: ctx, repository, arch
func (_m *MockPackageService) GetRepositoryIndex(ctx context.Context, repository string, arch string) (*apk.RepositoryIndex, error) {
	ret := _m.Called(ctx, repository, arch)

	if len(ret) == 0 {
		panic("no return value specified for GetRepositoryIndex")
	}

	var r0 *apk.RepositoryIndex
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*apk.RepositoryIndex, error)); ok {
		return rf(ctx, repository, arch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *apk.RepositoryIndex); ok {
		r0 = rf(ctx, repository, arch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apk.RepositoryIndex)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repository, arch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_GetRepositoryIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepositoryIndex'
type MockPackageService_GetRepositoryIndex_Call struct {
	*mock.Call
}

// GetRepositoryIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
//   - arch string
func (_e *MockPackageService_Expecter) GetRepositoryIndex(ctx interface{}, repository interface{}, arch interface{}) *MockPackageService_GetRepositoryIndex_Call {
	return &MockPackageService_GetRepositoryIndex_Call{Call: _e.mock.On("GetRepositoryIndex", ctx, repository, arch)}
}

func (_c *MockPackageService_GetRepositoryIndex_Call) Run(run func(ctx context.Context, repository string, arch string)) *MockPackageService_GetRepositoryIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPackageService_GetRepositoryIndex_Call) Return(_a0 *apk.RepositoryIndex, _a1 error) *MockPackageService_GetRepositoryIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_GetRepositoryIndex_Call) RunAndReturn(run func(context.Context, string, string) (*apk.RepositoryIndex, error)) *MockPackageService_GetRepositoryIndex_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPackages provides a mock function with given fields: ctx, query, filters
func (_m *MockPackageService) SearchPackages(ctx context.Context, query string, filters apk.SearchFilters) ([]apk.Package, error) {
	ret := _m.Called(ctx, query, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchPackages")
	}

	var r0 []apk.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, apk.SearchFilters) ([]apk.Package, error)); ok {
		return rf(ctx, query, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, apk.SearchFilters) []apk.Package); ok {
		r0 = rf(ctx, query, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apk.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, apk.SearchFilters) error); ok {
		r1 = rf(ctx, query, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_SearchPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPackages'
type MockPackageService_SearchPackages_Call struct {
	*mock.Call
}

// SearchPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters apk.SearchFilters
func (_e *MockPackageService_Expecter) SearchPackages(ctx interface{}, query interface{}, filters interface{}) *MockPackageService_SearchPackages_Call {
	return &MockPackageService_SearchPackages_Call{Call: _e.mock.On("SearchPackages", ctx, query, filters)}
}

func (_c *MockPackageService_SearchPackages_Call) Run(run func(ctx context.Context, query string, filters apk.SearchFilters)) *MockPackageService_SearchPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(apk.SearchFilters))
	})
	return _c
}

func (_c *MockPackageService_SearchPackages_Call) Return(_a0 []apk.Package, _a1 error) *MockPackageService_SearchPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_SearchPackages_Call) RunAndReturn(run func(context.Context, string, apk.SearchFilters) ([]apk.Package, error)) *MockPackageService_SearchPackages_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySignature provides a mock function with given fields: ctx, pkg, signature
func (_m *MockPackageService) VerifySignature(ctx context.Context, pkg *apk.Package, signature []byte) error {
	ret := _m.Called(ctx, pkg, signature)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *apk.Package, []byte) error); ok {
		r0 = rf(ctx, pkg, signature)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPackageService_VerifySignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignature'
type MockPackageService_VerifySignature_Call struct {
	*mock.Call
}

// VerifySignature is a helper method to define mock.On call
//   - ctx context.Context
//   - pkg *apk.Package
//   - signature []byte
func (_e *MockPackageService_Expecter) VerifySignature(ctx interface{}, pkg interface{}, signature interface{}) *MockPackageService_VerifySignature_Call {
	return &MockPackageService_VerifySignature_Call{Call: _e.mock.On("VerifySignature", ctx, pkg, signature)}
}

func (_c *MockPackageService_VerifySignature_Call) Run(run func(ctx context.Context, pkg *apk.Package, signature []byte)) *MockPackageService_VerifySignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*apk.Package), args[2].([]byte))
	})
	return _c
}

func (_c *MockPackageService_VerifySignature_Call) Return(_a0 error) *MockPackageService_VerifySignature_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackageService_VerifySignature_Call) RunAndReturn(run func(context.Context, *apk.Package, []byte) error) *MockPackageService_VerifySignature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackageService creates a new instance of MockPackageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageService {
	mock := &MockPackageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
