package app

import (
	"fmt"
	"os"
	"time"

	"github.com/gofiber/fiber/v2"
	fiberSwagger "github.com/swaggo/fiber-swagger"

	// Import new adapter structure
	"proxynd/cache"
	fiberHandlers "proxynd/internal/adapters/http/fiber/handlers"
	enterpriseHandlers "proxynd/internal/adapters/http/fiber/handlers/enterprise"
	fiberMiddleware "proxynd/internal/adapters/http/fiber/middleware"
	fiberRouters "proxynd/internal/adapters/http/fiber/routers"
	"proxynd/internal/config"

	// Swagger docs - auto-generated by swag init
	_ "proxynd/docs"

	// TODO: HEXAGONAL_MIGRATION - Remove legacy imports after full migration
	"proxynd/internal/handlers-legacy"
	"proxynd/internal/logging"
	middlewares "proxynd/internal/middleware-legacy"
	"proxynd/internal/routers"
)

// RouteConfig holds configuration for route setup
type RouteConfig struct {
	UseNewArchitecture bool // Feature flag for gradual migration
	UnifiedConfig      *config.UnifiedConfig
	Logger             logging.Logger
	Container          *Container // Dependency injection container
}

// SetupRoutes configures all application routes with hybrid old/new architecture
func SetupRoutes(app *fiber.App, config *RouteConfig) {
	logger := config.Logger
	if logger == nil {
		logger = logging.GetLogger()
	}

	logger.Info("Setting up routes",
		logging.Bool("new_architecture", config.UseNewArchitecture))

	// HEXAGONAL_MIGRATION Phase 2c - New architecture is now default
	// Legacy mode retained for emergency rollback only
	if config.UseNewArchitecture {
		setupNewArchitectureRoutes(app, config)
	} else {
		setupLegacyRoutes(app, config)
	}
}

// setupNewArchitectureRoutes configures routes using new hexagonal architecture
func setupNewArchitectureRoutes(app *fiber.App, config *RouteConfig) {
	logger := config.Logger

	// Setup middlewares using new architecture
	setupNewMiddlewares(app, config)

	// Health routes using new architecture
	logger.Info("Setting up health routes (new architecture)")
	fiberRouters.HealthRouterWithConfig(app, config.UnifiedConfig)

	// API routes
	api := app.Group("/api")
	v1 := api.Group("/v1")

	// Proxy routes using hybrid approach
	logger.Info("Setting up proxy routes (hybrid architecture)")
	fiberRouters.ProxyRouter(app)   // New structure
	fiberRouters.ProxyRouterV3(app) // V3 routes are added to main app

	// Search routes
	logger.Info("Setting up search routes")
	v1.Get("/search", fiberHandlers.SearchHandlerFunc)

	// Pool routes
	logger.Info("Setting up pool routes")
	fiberRouters.PoolRouter(app)

	// Cache routes
	logger.Info("Setting up cache routes")
	fiberRouters.CacheRouter(app)

	// Initialize cache manager for API v1 stats
	setupCacheManagerForAPI(config, logger)

	// API v1 routes (for WebUI integration)

	// WebUI static file serving (Enterprise/Cloud only)
	logger.Info("Setting up WebUI routes")
	fiberRouters.SetupWebUIRoutes(app, getEdition())
	logger.Info("Setting up API v1 routes")
	fiberRouters.SetupAPIv1Routes(app, config.UnifiedConfig)

	// Enterprise API routes (47 endpoints for RBAC, Audit, Analytics, Security)
	logger.Info("Setting up Enterprise API routes")
	// Initialize enterprise features for license validation
	configDir := os.Getenv("CONFIG_DIR")
	if configDir == "" {
		configDir = "./tmp/config"
	}
	enterpriseFeatures := InitEnterpriseFeatures(configDir)
	fiberRouters.SetupEnterpriseRoutes(app, enterpriseFeatures)

	// Load development fixtures if available (in dev mode)
	loadEnterpriseFixtures(logger)

	// Swagger API documentation
	logger.Info("Setting up Swagger API documentation")
	app.Get("/swagger/*", fiberSwagger.WrapHandler)
	app.Get("/api/docs/*", fiberSwagger.WrapHandler)

	// Redirect /swagger to /swagger/index.html
	app.Get("/swagger", func(c *fiber.Ctx) error {
		return c.Redirect("/swagger/index.html", 301)
	})

	// Redirect /api/docs to /api/docs/index.html
	app.Get("/api/docs", func(c *fiber.Ctx) error {
		return c.Redirect("/api/docs/index.html", 301)
	})

	// Alias /api/v1/docs to Swagger UI for better discoverability
	app.Get("/api/v1/docs", func(c *fiber.Ctx) error {
		return c.Redirect("/swagger/index.html", 301)
	})
	app.Get("/api/v1/docs/*", func(c *fiber.Ctx) error {
		// Redirect /api/v1/docs/* to /swagger/*
		path := c.Params("*")
		return c.Redirect("/swagger/"+path, 301)
	})

	logger.Info("Swagger UI available at /swagger/index.html, /api/docs/index.html and /api/v1/docs")

	// Metrics routes
	logger.Info("Setting up metrics routes")
	routers.MetricsRouter(app, config.UnifiedConfig)

	// Ansible routes (Galaxy v3 API)
	logger.Info("Setting up Ansible routes")
	setupAnsibleRoutes(app, config)

	// TODO: HEXAGONAL_MIGRATION - Add other routers as they are migrated
	logger.Info("New architecture routes setup completed")
}

// setupLegacyRoutes configures routes using legacy structure (fallback)
func setupLegacyRoutes(app *fiber.App, config *RouteConfig) {
	logger := config.Logger
	logger.Info("Setting up legacy routes")

	// Legacy middleware setup
	setupLegacyMiddlewares(app, config)

	// Legacy routers - maintain existing behavior
	routers.HealthRouterWithConfig(app, config.UnifiedConfig)
	routers.ProxyRouter(app)
	routers.ProxyRouterV3(app) // V3 routes use main app

	app.Get("/api/v1/search", handlers.SearchHandler)

	routers.PoolRouter(app)
	routers.CacheRouter(app)
	routers.ConfigRouter(app)
	routers.StatusRouter(app)
	routers.UserRouter(app)
	routers.AuthRouter(app)
	routers.MetricsRouter(app, config.UnifiedConfig)
	routers.WebhookRouter(app)
	// TODO: HEXAGONAL_MIGRATION - Add container support when available
	// routers.ContainerProxyRouterSetup(app, container) // Requires container parameter
	routers.APKMirrorRouter(app)
	routers.APKVerificationRouter(app)
	routers.UnifiedRouterV1(app)

	logger.Info("Legacy routes setup completed")
}

// setupNewMiddlewares configures middlewares using new architecture
func setupNewMiddlewares(app *fiber.App, config *RouteConfig) {
	logger := config.Logger
	logger.Info("Setting up middlewares (new architecture)")

	// Basic middlewares - error handling and recovery
	app.Use(fiberMiddleware.ErrorRecovery())
	logger.Info("Middleware registered: ErrorRecovery")

	app.Use(fiberMiddleware.ErrorHandler())
	logger.Info("Middleware registered: ErrorHandler")

	// Access logging
	app.Use(fiberMiddleware.DefaultAccessLogMiddleware())
	logger.Info("Middleware registered: AccessLog")

	// Security middlewares
	app.Use(fiberMiddleware.SecurityHeaders())
	logger.Info("Middleware registered: SecurityHeaders")

	// Rate limiting using enhanced rate limiter
	app.Use(fiberMiddleware.NewEnhancedRateLimiter())
	logger.Info("Middleware registered: EnhancedRateLimiter")

	// Authentication middleware (conditional)
	// Note: JWT authentication can be enabled via OAuth2 configuration
	// For now, skip JWT middleware in new architecture until auth config is properly structured
	// TODO: HEXAGONAL_MIGRATION - Add proper auth middleware integration when OAuth2Config is available

	logger.Info("New middleware setup completed",
		logging.Int("middleware_count", 5))
}

// setupLegacyMiddlewares configures middlewares using legacy structure
func setupLegacyMiddlewares(app *fiber.App, config *RouteConfig) {
	logger := config.Logger
	logger.Info("Setting up legacy middlewares")

	// Basic middlewares
	app.Use(middlewares.ErrorRecovery())
	app.Use(middlewares.ErrorHandler()) // Maps DomainError to proper HTTP status codes
	app.Use(middlewares.DefaultAccessLogMiddleware())

	// Security middlewares
	app.Use(middlewares.SecurityHeaders())
	app.Use(middlewares.RateLimit())

	// Authentication middleware (conditional)
	// TODO: HEXAGONAL_MIGRATION - Add auth config support
	// if config.UnifiedConfig != nil && config.UnifiedConfig.Auth.Enabled {
	//	app.Use(middlewares.JWTAuthMiddleware())
	// }

	logger.Info("Legacy middlewares setup completed")
}

// InitializeRouteConfig creates a default route configuration
func InitializeRouteConfig(unifiedConfig *config.UnifiedConfig, useNewArch bool, container *Container) *RouteConfig {
	return &RouteConfig{
		UseNewArchitecture: useNewArch,
		UnifiedConfig:      unifiedConfig,
		Logger:             logging.GetLogger(),
		Container:          container,
	}
}

// HEXAGONAL_MIGRATION - Migration utilities (Phase 2c complete)
// These functions allow runtime switching for testing/rollback

// EnableNewArchitecture switches to new architecture mode (default since Phase 2c)
func (rc *RouteConfig) EnableNewArchitecture() {
	rc.UseNewArchitecture = true
	rc.Logger.Info("Switched to new architecture mode")
}

// DisableNewArchitecture switches to legacy mode (for rollback)
func (rc *RouteConfig) DisableNewArchitecture() {
	rc.UseNewArchitecture = false
	rc.Logger.Info("Switched to legacy architecture mode")
}

// GetMigrationStatus returns current migration status
func (rc *RouteConfig) GetMigrationStatus() map[string]interface{} {
	// Calculate migration progress dynamically based on completed phases
	// Phase 1: Files copied (25%)
	// Phase 2a: Middleware integrated (25%)
	// Phase 2b: Routers migrated (25%)
	// Phase 2c: Default enabled (25%)
	// Phase 3: Legacy removed (not started = 0%)
	progress := calculateMigrationProgress()

	return map[string]interface{}{
		"new_architecture_enabled": rc.UseNewArchitecture,
		"migration_phase":          getCurrentMigrationPhase(),
		"default_mode":             getDefaultMode(rc.UseNewArchitecture),
		"legacy_fallback_active":   true, // Still available for rollback
		"migration_progress":       progress,
		"phases": map[string]interface{}{
			"phase_1_files_copied":     true,  // 25%
			"phase_2a_middleware":      true,  // 25%
			"phase_2b_routers":         true,  // 25%
			"phase_2c_default_enabled": true,  // 25%
			"phase_3_legacy_removed":   false, // 0% (pending)
		},
	}
}

// calculateMigrationProgress computes the current migration progress percentage
func calculateMigrationProgress() string {
	// Each phase contributes 20% (5 phases total)
	const (
		phase1Complete  = true  // Files copied
		phase2aComplete = true  // Middleware integrated
		phase2bComplete = true  // Routers migrated
		phase2cComplete = true  // Default enabled (completed 2025-11-27)
		phase3Complete  = false // Legacy removed (pending)
	)

	progress := 0
	if phase1Complete {
		progress += 20
	}
	if phase2aComplete {
		progress += 20
	}
	if phase2bComplete {
		progress += 20
	}
	if phase2cComplete {
		progress += 20
	}
	if phase3Complete {
		progress += 20
	}

	// Format as percentage string
	return fmt.Sprintf("%d%%", progress)
}

// getCurrentMigrationPhase returns the current active migration phase
func getCurrentMigrationPhase() string {
	// Update this when phases progress
	const phase3Complete = false

	if !phase3Complete {
		return "phase_2c_complete" // Updated 2025-11-27
	}
	return "phase_3_complete"
}

// getDefaultMode returns the default architecture mode
func getDefaultMode(useNewArchitecture bool) string {
	if useNewArchitecture {
		return "new_architecture"
	}
	return "legacy_architecture"
}

// setupCacheManagerForAPI initializes and sets cache manager for API v1 stats
func setupCacheManagerForAPI(config *RouteConfig, logger logging.Logger) {
	if config == nil || config.UnifiedConfig == nil {
		logger.Warn("Cannot initialize cache manager: config is nil")
		return
	}

	// Determine storage directory
	storageDir := "./storage"
	if config.UnifiedConfig.Cache.Backend == "file" && config.UnifiedConfig.Cache.File.Directory != "" {
		storageDir = config.UnifiedConfig.Cache.File.Directory
	}

	// Create filesystem backend
	cacheBackend, err := cache.NewFileSystemBackend(storageDir)
	if err != nil {
		logger.Warn("Failed to create cache backend for API stats",
			logging.F("error", err),
			logging.F("storage_dir", storageDir))
		return
	}

	// Create cache options
	cacheOptions := cache.CacheOptions{
		MaxSize:    1024 * 1024 * 1024, // 1GB default
		DefaultTTL: time.Hour,
		BasePath:   storageDir,
	}

	// Create cache manager
	cacheManager := cache.NewManager(cacheBackend, cacheOptions)

	// Set cache manager for API v1 routes
	fiberRouters.SetCacheManager(cacheManager)

	logger.Info("Cache manager initialized for API v1 stats",
		logging.F("backend", "filesystem"),
		logging.F("storage_dir", storageDir))
}

// loadEnterpriseFixtures loads development fixtures for enterprise API
func loadEnterpriseFixtures(logger logging.Logger) {
	// Only load in development mode
	if os.Getenv("GO_ENV") == "production" {
		return
	}

	fixturesDir := "./tmp/fixtures"
	if _, err := os.Stat(fixturesDir); os.IsNotExist(err) {
		logger.Debug("Enterprise fixtures directory not found, skipping",
			logging.F("dir", fixturesDir))
		return
	}

	logger.Info("Loading enterprise development fixtures",
		logging.F("dir", fixturesDir))

	// Fixture loading is best-effort in dev mode
	// Failures are logged but don't stop the server
	loader := enterpriseHandlers.NewFixtureLoader(fixturesDir, logger)
	if loader.IsAvailable() {
		if err := loader.LoadAll(); err != nil {
			logger.Warn("Failed to load some enterprise fixtures",
				logging.F("error", err))
		}
	}
}

// setupAnsibleRoutes configures Ansible Galaxy v3 API routes
func setupAnsibleRoutes(app *fiber.App, config *RouteConfig) {
	logger := config.Logger

	// TODO: Initialize AnsibleHandler with proper dependencies
	// For now, this is a placeholder that logs a warning
	logger.Info("Ansible routes setup - handler initialization pending")

	// Ansible handler will be initialized here once dependencies are ready
	// Example:
	// handler := ansible.NewAnsibleHandler(hostedDriver, cfg, logger)
	// fiberRouters.RegisterAnsibleRoutes(app, handler)
}
