// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockBlobManager is an autogenerated mock type for the BlobManager type
type MockBlobManager struct {
	mock.Mock
}

type MockBlobManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobManager) EXPECT() *MockBlobManager_Expecter {
	return &MockBlobManager_Expecter{mock: &_m.Mock}
}

// DeleteBlob provides a mock function with given fields: ctx, digest
func (_m *MockBlobManager) DeleteBlob(ctx context.Context, digest string) error {
	ret := _m.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, digest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobManager_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type MockBlobManager_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
func (_e *MockBlobManager_Expecter) DeleteBlob(ctx interface{}, digest interface{}) *MockBlobManager_DeleteBlob_Call {
	return &MockBlobManager_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", ctx, digest)}
}

func (_c *MockBlobManager_DeleteBlob_Call) Run(run func(ctx context.Context, digest string)) *MockBlobManager_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlobManager_DeleteBlob_Call) Return(_a0 error) *MockBlobManager_DeleteBlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobManager_DeleteBlob_Call) RunAndReturn(run func(context.Context, string) error) *MockBlobManager_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function with given fields: ctx, digest
func (_m *MockBlobManager) GetBlob(ctx context.Context, digest string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, digest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlobManager_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type MockBlobManager_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
func (_e *MockBlobManager_Expecter) GetBlob(ctx interface{}, digest interface{}) *MockBlobManager_GetBlob_Call {
	return &MockBlobManager_GetBlob_Call{Call: _e.mock.On("GetBlob", ctx, digest)}
}

func (_c *MockBlobManager_GetBlob_Call) Run(run func(ctx context.Context, digest string)) *MockBlobManager_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlobManager_GetBlob_Call) Return(_a0 io.ReadCloser, _a1 error) *MockBlobManager_GetBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlobManager_GetBlob_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockBlobManager_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StoreBlob provides a mock function with given fields: ctx, reader
func (_m *MockBlobManager) StoreBlob(ctx context.Context, reader io.Reader) (string, error) {
	ret := _m.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for StoreBlob")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (string, error)); ok {
		return rf(ctx, reader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) string); ok {
		r0 = rf(ctx, reader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlobManager_StoreBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreBlob'
type MockBlobManager_StoreBlob_Call struct {
	*mock.Call
}

// StoreBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.Reader
func (_e *MockBlobManager_Expecter) StoreBlob(ctx interface{}, reader interface{}) *MockBlobManager_StoreBlob_Call {
	return &MockBlobManager_StoreBlob_Call{Call: _e.mock.On("StoreBlob", ctx, reader)}
}

func (_c *MockBlobManager_StoreBlob_Call) Run(run func(ctx context.Context, reader io.Reader)) *MockBlobManager_StoreBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockBlobManager_StoreBlob_Call) Return(_a0 string, _a1 error) *MockBlobManager_StoreBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlobManager_StoreBlob_Call) RunAndReturn(run func(context.Context, io.Reader) (string, error)) *MockBlobManager_StoreBlob_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBlob provides a mock function with given fields: ctx, digest, reader
func (_m *MockBlobManager) ValidateBlob(ctx context.Context, digest string, reader io.Reader) error {
	ret := _m.Called(ctx, digest, reader)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, digest, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobManager_ValidateBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBlob'
type MockBlobManager_ValidateBlob_Call struct {
	*mock.Call
}

// ValidateBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
//   - reader io.Reader
func (_e *MockBlobManager_Expecter) ValidateBlob(ctx interface{}, digest interface{}, reader interface{}) *MockBlobManager_ValidateBlob_Call {
	return &MockBlobManager_ValidateBlob_Call{Call: _e.mock.On("ValidateBlob", ctx, digest, reader)}
}

func (_c *MockBlobManager_ValidateBlob_Call) Run(run func(ctx context.Context, digest string, reader io.Reader)) *MockBlobManager_ValidateBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockBlobManager_ValidateBlob_Call) Return(_a0 error) *MockBlobManager_ValidateBlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobManager_ValidateBlob_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockBlobManager_ValidateBlob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlobManager creates a new instance of MockBlobManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobManager {
	mock := &MockBlobManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
