// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	docker "proxynd/internal/domain/docker"
)

// MockRegistryService is an autogenerated mock type for the RegistryService type
type MockRegistryService struct {
	mock.Mock
}

type MockRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryService) EXPECT() *MockRegistryService_Expecter {
	return &MockRegistryService_Expecter{mock: &_m.Mock}
}

// GetManifest provides a mock function with given fields: ctx, repository, tag
func (_m *MockRegistryService) GetManifest(ctx context.Context, repository string, tag string) (*docker.Manifest, error) {
	ret := _m.Called(ctx, repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *docker.Manifest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*docker.Manifest, error)); ok {
		return rf(ctx, repository, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *docker.Manifest); ok {
		r0 = rf(ctx, repository, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*docker.Manifest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repository, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryService_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type MockRegistryService_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
//   - tag string
func (_e *MockRegistryService_Expecter) GetManifest(ctx interface{}, repository interface{}, tag interface{}) *MockRegistryService_GetManifest_Call {
	return &MockRegistryService_GetManifest_Call{Call: _e.mock.On("GetManifest", ctx, repository, tag)}
}

func (_c *MockRegistryService_GetManifest_Call) Run(run func(ctx context.Context, repository string, tag string)) *MockRegistryService_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRegistryService_GetManifest_Call) Return(_a0 *docker.Manifest, _a1 error) *MockRegistryService_GetManifest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryService_GetManifest_Call) RunAndReturn(run func(context.Context, string, string) (*docker.Manifest, error)) *MockRegistryService_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function with given fields: ctx, repository
func (_m *MockRegistryService) ListTags(ctx context.Context, repository string) (*docker.TagList, error) {
	ret := _m.Called(ctx, repository)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 *docker.TagList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*docker.TagList, error)); ok {
		return rf(ctx, repository)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *docker.TagList); ok {
		r0 = rf(ctx, repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*docker.TagList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repository)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockRegistryService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
func (_e *MockRegistryService_Expecter) ListTags(ctx interface{}, repository interface{}) *MockRegistryService_ListTags_Call {
	return &MockRegistryService_ListTags_Call{Call: _e.mock.On("ListTags", ctx, repository)}
}

func (_c *MockRegistryService_ListTags_Call) Run(run func(ctx context.Context, repository string)) *MockRegistryService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryService_ListTags_Call) Return(_a0 *docker.TagList, _a1 error) *MockRegistryService_ListTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryService_ListTags_Call) RunAndReturn(run func(context.Context, string) (*docker.TagList, error)) *MockRegistryService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PushManifest provides a mock function with given fields: ctx, repository, tag, manifest
func (_m *MockRegistryService) PushManifest(ctx context.Context, repository string, tag string, manifest *docker.Manifest) error {
	ret := _m.Called(ctx, repository, tag, manifest)

	if len(ret) == 0 {
		panic("no return value specified for PushManifest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *docker.Manifest) error); ok {
		r0 = rf(ctx, repository, tag, manifest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistryService_PushManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushManifest'
type MockRegistryService_PushManifest_Call struct {
	*mock.Call
}

// PushManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
//   - tag string
//   - manifest *docker.Manifest
func (_e *MockRegistryService_Expecter) PushManifest(ctx interface{}, repository interface{}, tag interface{}, manifest interface{}) *MockRegistryService_PushManifest_Call {
	return &MockRegistryService_PushManifest_Call{Call: _e.mock.On("PushManifest", ctx, repository, tag, manifest)}
}

func (_c *MockRegistryService_PushManifest_Call) Run(run func(ctx context.Context, repository string, tag string, manifest *docker.Manifest)) *MockRegistryService_PushManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*docker.Manifest))
	})
	return _c
}

func (_c *MockRegistryService_PushManifest_Call) Return(_a0 error) *MockRegistryService_PushManifest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistryService_PushManifest_Call) RunAndReturn(run func(context.Context, string, string, *docker.Manifest) error) *MockRegistryService_PushManifest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateManifest provides a mock function with given fields: ctx, manifest
func (_m *MockRegistryService) ValidateManifest(ctx context.Context, manifest *docker.Manifest) error {
	ret := _m.Called(ctx, manifest)

	if len(ret) == 0 {
		panic("no return value specified for ValidateManifest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *docker.Manifest) error); ok {
		r0 = rf(ctx, manifest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistryService_ValidateManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateManifest'
type MockRegistryService_ValidateManifest_Call struct {
	*mock.Call
}

// ValidateManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - manifest *docker.Manifest
func (_e *MockRegistryService_Expecter) ValidateManifest(ctx interface{}, manifest interface{}) *MockRegistryService_ValidateManifest_Call {
	return &MockRegistryService_ValidateManifest_Call{Call: _e.mock.On("ValidateManifest", ctx, manifest)}
}

func (_c *MockRegistryService_ValidateManifest_Call) Run(run func(ctx context.Context, manifest *docker.Manifest)) *MockRegistryService_ValidateManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*docker.Manifest))
	})
	return _c
}

func (_c *MockRegistryService_ValidateManifest_Call) Return(_a0 error) *MockRegistryService_ValidateManifest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistryService_ValidateManifest_Call) RunAndReturn(run func(context.Context, *docker.Manifest) error) *MockRegistryService_ValidateManifest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistryService creates a new instance of MockRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryService {
	mock := &MockRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
