// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pip "proxynd/internal/domain/pip"
)

// MockPackageService is an autogenerated mock type for the PackageService type
type MockPackageService struct {
	mock.Mock
}

type MockPackageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageService) EXPECT() *MockPackageService_Expecter {
	return &MockPackageService_Expecter{mock: &_m.Mock}
}

// GetPackageFiles provides a mock function with given fields: ctx, packageName
func (_m *MockPackageService) GetPackageFiles(ctx context.Context, packageName string) ([]pip.PackageFile, error) {
	ret := _m.Called(ctx, packageName)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageFiles")
	}

	var r0 []pip.PackageFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]pip.PackageFile, error)); ok {
		return rf(ctx, packageName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []pip.PackageFile); ok {
		r0 = rf(ctx, packageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pip.PackageFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, packageName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_GetPackageFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageFiles'
type MockPackageService_GetPackageFiles_Call struct {
	*mock.Call
}

// GetPackageFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - packageName string
func (_e *MockPackageService_Expecter) GetPackageFiles(ctx interface{}, packageName interface{}) *MockPackageService_GetPackageFiles_Call {
	return &MockPackageService_GetPackageFiles_Call{Call: _e.mock.On("GetPackageFiles", ctx, packageName)}
}

func (_c *MockPackageService_GetPackageFiles_Call) Run(run func(ctx context.Context, packageName string)) *MockPackageService_GetPackageFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPackageService_GetPackageFiles_Call) Return(_a0 []pip.PackageFile, _a1 error) *MockPackageService_GetPackageFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_GetPackageFiles_Call) RunAndReturn(run func(context.Context, string) ([]pip.PackageFile, error)) *MockPackageService_GetPackageFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageMetadata provides a mock function with given fields: ctx, packageName, version
func (_m *MockPackageService) GetPackageMetadata(ctx context.Context, packageName string, version string) (*pip.PackageMetadata, error) {
	ret := _m.Called(ctx, packageName, version)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageMetadata")
	}

	var r0 *pip.PackageMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*pip.PackageMetadata, error)); ok {
		return rf(ctx, packageName, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *pip.PackageMetadata); ok {
		r0 = rf(ctx, packageName, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pip.PackageMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, packageName, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_GetPackageMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageMetadata'
type MockPackageService_GetPackageMetadata_Call struct {
	*mock.Call
}

// GetPackageMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - packageName string
//   - version string
func (_e *MockPackageService_Expecter) GetPackageMetadata(ctx interface{}, packageName interface{}, version interface{}) *MockPackageService_GetPackageMetadata_Call {
	return &MockPackageService_GetPackageMetadata_Call{Call: _e.mock.On("GetPackageMetadata", ctx, packageName, version)}
}

func (_c *MockPackageService_GetPackageMetadata_Call) Run(run func(ctx context.Context, packageName string, version string)) *MockPackageService_GetPackageMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPackageService_GetPackageMetadata_Call) Return(_a0 *pip.PackageMetadata, _a1 error) *MockPackageService_GetPackageMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_GetPackageMetadata_Call) RunAndReturn(run func(context.Context, string, string) (*pip.PackageMetadata, error)) *MockPackageService_GetPackageMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPackages provides a mock function with given fields: ctx, query, filters
func (_m *MockPackageService) SearchPackages(ctx context.Context, query string, filters pip.SearchFilters) ([]pip.PackageMetadata, error) {
	ret := _m.Called(ctx, query, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchPackages")
	}

	var r0 []pip.PackageMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pip.SearchFilters) ([]pip.PackageMetadata, error)); ok {
		return rf(ctx, query, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pip.SearchFilters) []pip.PackageMetadata); ok {
		r0 = rf(ctx, query, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pip.PackageMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pip.SearchFilters) error); ok {
		r1 = rf(ctx, query, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackageService_SearchPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPackages'
type MockPackageService_SearchPackages_Call struct {
	*mock.Call
}

// SearchPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters pip.SearchFilters
func (_e *MockPackageService_Expecter) SearchPackages(ctx interface{}, query interface{}, filters interface{}) *MockPackageService_SearchPackages_Call {
	return &MockPackageService_SearchPackages_Call{Call: _e.mock.On("SearchPackages", ctx, query, filters)}
}

func (_c *MockPackageService_SearchPackages_Call) Run(run func(ctx context.Context, query string, filters pip.SearchFilters)) *MockPackageService_SearchPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pip.SearchFilters))
	})
	return _c
}

func (_c *MockPackageService_SearchPackages_Call) Return(_a0 []pip.PackageMetadata, _a1 error) *MockPackageService_SearchPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackageService_SearchPackages_Call) RunAndReturn(run func(context.Context, string, pip.SearchFilters) ([]pip.PackageMetadata, error)) *MockPackageService_SearchPackages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackageService creates a new instance of MockPackageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageService {
	mock := &MockPackageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
