// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	alerts "proxynd/alerts"
	configs "proxynd/configs"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWebhookAdapter is an autogenerated mock type for the WebhookAdapter type
type MockWebhookAdapter struct {
	mock.Mock
}

type MockWebhookAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookAdapter) EXPECT() *MockWebhookAdapter_Expecter {
	return &MockWebhookAdapter_Expecter{mock: &_m.Mock}
}

// FormatMessage provides a mock function with given fields: event, format
func (_m *MockWebhookAdapter) FormatMessage(event *alerts.AlertEvent, format string) (interface{}, error) {
	ret := _m.Called(event, format)

	if len(ret) == 0 {
		panic("no return value specified for FormatMessage")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*alerts.AlertEvent, string) (interface{}, error)); ok {
		return rf(event, format)
	}
	if rf, ok := ret.Get(0).(func(*alerts.AlertEvent, string) interface{}); ok {
		r0 = rf(event, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*alerts.AlertEvent, string) error); ok {
		r1 = rf(event, format)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookAdapter_FormatMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatMessage'
type MockWebhookAdapter_FormatMessage_Call struct {
	*mock.Call
}

// FormatMessage is a helper method to define mock.On call
//   - event *alerts.AlertEvent
//   - format string
func (_e *MockWebhookAdapter_Expecter) FormatMessage(event interface{}, format interface{}) *MockWebhookAdapter_FormatMessage_Call {
	return &MockWebhookAdapter_FormatMessage_Call{Call: _e.mock.On("FormatMessage", event, format)}
}

func (_c *MockWebhookAdapter_FormatMessage_Call) Run(run func(event *alerts.AlertEvent, format string)) *MockWebhookAdapter_FormatMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*alerts.AlertEvent), args[1].(string))
	})
	return _c
}

func (_c *MockWebhookAdapter_FormatMessage_Call) Return(_a0 interface{}, _a1 error) *MockWebhookAdapter_FormatMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookAdapter_FormatMessage_Call) RunAndReturn(run func(*alerts.AlertEvent, string) (interface{}, error)) *MockWebhookAdapter_FormatMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockWebhookAdapter) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWebhookAdapter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockWebhookAdapter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockWebhookAdapter_Expecter) Name() *MockWebhookAdapter_Name_Call {
	return &MockWebhookAdapter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockWebhookAdapter_Name_Call) Run(run func()) *MockWebhookAdapter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookAdapter_Name_Call) Return(_a0 string) *MockWebhookAdapter_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookAdapter_Name_Call) RunAndReturn(run func() string) *MockWebhookAdapter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, event, endpoint
func (_m *MockWebhookAdapter) Send(ctx context.Context, event *alerts.AlertEvent, endpoint configs.WebhookEndpointConfig) error {
	ret := _m.Called(ctx, event, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *alerts.AlertEvent, configs.WebhookEndpointConfig) error); ok {
		r0 = rf(ctx, event, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookAdapter_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockWebhookAdapter_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - event *alerts.AlertEvent
//   - endpoint configs.WebhookEndpointConfig
func (_e *MockWebhookAdapter_Expecter) Send(ctx interface{}, event interface{}, endpoint interface{}) *MockWebhookAdapter_Send_Call {
	return &MockWebhookAdapter_Send_Call{Call: _e.mock.On("Send", ctx, event, endpoint)}
}

func (_c *MockWebhookAdapter_Send_Call) Run(run func(ctx context.Context, event *alerts.AlertEvent, endpoint configs.WebhookEndpointConfig)) *MockWebhookAdapter_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*alerts.AlertEvent), args[2].(configs.WebhookEndpointConfig))
	})
	return _c
}

func (_c *MockWebhookAdapter_Send_Call) Return(_a0 error) *MockWebhookAdapter_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookAdapter_Send_Call) RunAndReturn(run func(context.Context, *alerts.AlertEvent, configs.WebhookEndpointConfig) error) *MockWebhookAdapter_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedFormats provides a mock function with no fields
func (_m *MockWebhookAdapter) SupportedFormats() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedFormats")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockWebhookAdapter_SupportedFormats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedFormats'
type MockWebhookAdapter_SupportedFormats_Call struct {
	*mock.Call
}

// SupportedFormats is a helper method to define mock.On call
func (_e *MockWebhookAdapter_Expecter) SupportedFormats() *MockWebhookAdapter_SupportedFormats_Call {
	return &MockWebhookAdapter_SupportedFormats_Call{Call: _e.mock.On("SupportedFormats")}
}

func (_c *MockWebhookAdapter_SupportedFormats_Call) Run(run func()) *MockWebhookAdapter_SupportedFormats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookAdapter_SupportedFormats_Call) Return(_a0 []string) *MockWebhookAdapter_SupportedFormats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookAdapter_SupportedFormats_Call) RunAndReturn(run func() []string) *MockWebhookAdapter_SupportedFormats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookAdapter creates a new instance of MockWebhookAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookAdapter {
	mock := &MockWebhookAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
