// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "ProxyND API",
        "description": "High-performance package manager proxy/mirror server",
        "contact": {
            "name": "ProxyND Support",
            "url": "https://github.com/ScriptonBasestar/proxynd/issues",
            "email": "support@proxynd.io"
        },
        "license": {
            "name": "AGPL-3.0",
            "url": "https://www.gnu.org/licenses/agpl-3.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "schemes": ["http", "https"],
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "ProxyND API",
	Description:      "High-performance package manager proxy/mirror server supporting Maven, NPM, APT, Docker Registry, PyPI, YUM, and APK. Enterprise features include RBAC, audit logging, analytics, security scanning, and alerting.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
