// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAuthenticatedProxyHandler is an autogenerated mock type for the AuthenticatedProxyHandler type
type MockAuthenticatedProxyHandler struct {
	mock.Mock
}

type MockAuthenticatedProxyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticatedProxyHandler) EXPECT() *MockAuthenticatedProxyHandler_Expecter {
	return &MockAuthenticatedProxyHandler_Expecter{mock: &_m.Mock}
}

// BuildUpstreamURL provides a mock function with given fields: c
func (_m *MockAuthenticatedProxyHandler) BuildUpstreamURL(c *fiber.Ctx) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for BuildUpstreamURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticatedProxyHandler_BuildUpstreamURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildUpstreamURL'
type MockAuthenticatedProxyHandler_BuildUpstreamURL_Call struct {
	*mock.Call
}

// BuildUpstreamURL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) BuildUpstreamURL(c interface{}) *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call {
	return &MockAuthenticatedProxyHandler_BuildUpstreamURL_Call{Call: _e.mock.On("BuildUpstreamURL", c)}
}

func (_c *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call) Run(run func(c *fiber.Ctx)) *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call) Return(_a0 string, _a1 error) *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call) RunAndReturn(run func(*fiber.Ctx) (string, error)) *MockAuthenticatedProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCacheKey provides a mock function with given fields: c
func (_m *MockAuthenticatedProxyHandler) GenerateCacheKey(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCacheKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAuthenticatedProxyHandler_GenerateCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCacheKey'
type MockAuthenticatedProxyHandler_GenerateCacheKey_Call struct {
	*mock.Call
}

// GenerateCacheKey is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) GenerateCacheKey(c interface{}) *MockAuthenticatedProxyHandler_GenerateCacheKey_Call {
	return &MockAuthenticatedProxyHandler_GenerateCacheKey_Call{Call: _e.mock.On("GenerateCacheKey", c)}
}

func (_c *MockAuthenticatedProxyHandler_GenerateCacheKey_Call) Run(run func(c *fiber.Ctx)) *MockAuthenticatedProxyHandler_GenerateCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GenerateCacheKey_Call) Return(_a0 string) *MockAuthenticatedProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GenerateCacheKey_Call) RunAndReturn(run func(*fiber.Ctx) string) *MockAuthenticatedProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheTTL provides a mock function with given fields: c
func (_m *MockAuthenticatedProxyHandler) GetCacheTTL(c *fiber.Ctx) time.Duration {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) time.Duration); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockAuthenticatedProxyHandler_GetCacheTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheTTL'
type MockAuthenticatedProxyHandler_GetCacheTTL_Call struct {
	*mock.Call
}

// GetCacheTTL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) GetCacheTTL(c interface{}) *MockAuthenticatedProxyHandler_GetCacheTTL_Call {
	return &MockAuthenticatedProxyHandler_GetCacheTTL_Call{Call: _e.mock.On("GetCacheTTL", c)}
}

func (_c *MockAuthenticatedProxyHandler_GetCacheTTL_Call) Run(run func(c *fiber.Ctx)) *MockAuthenticatedProxyHandler_GetCacheTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GetCacheTTL_Call) Return(_a0 time.Duration) *MockAuthenticatedProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GetCacheTTL_Call) RunAndReturn(run func(*fiber.Ctx) time.Duration) *MockAuthenticatedProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpstreamAuth provides a mock function with given fields: c
func (_m *MockAuthenticatedProxyHandler) GetUpstreamAuth(c *fiber.Ctx) (string, string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetUpstreamAuth")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) (string, string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*fiber.Ctx) string); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*fiber.Ctx) error); ok {
		r2 = rf(c)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthenticatedProxyHandler_GetUpstreamAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpstreamAuth'
type MockAuthenticatedProxyHandler_GetUpstreamAuth_Call struct {
	*mock.Call
}

// GetUpstreamAuth is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) GetUpstreamAuth(c interface{}) *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call {
	return &MockAuthenticatedProxyHandler_GetUpstreamAuth_Call{Call: _e.mock.On("GetUpstreamAuth", c)}
}

func (_c *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call) Run(run func(c *fiber.Ctx)) *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call) Return(username string, password string, err error) *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call {
	_c.Call.Return(username, password, err)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call) RunAndReturn(run func(*fiber.Ctx) (string, string, error)) *MockAuthenticatedProxyHandler_GetUpstreamAuth_Call {
	_c.Call.Return(run)
	return _c
}

// HandleError provides a mock function with given fields: err, c
func (_m *MockAuthenticatedProxyHandler) HandleError(err error, c *fiber.Ctx) error {
	ret := _m.Called(err, c)

	if len(ret) == 0 {
		panic("no return value specified for HandleError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error, *fiber.Ctx) error); ok {
		r0 = rf(err, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthenticatedProxyHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockAuthenticatedProxyHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - err error
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) HandleError(err interface{}, c interface{}) *MockAuthenticatedProxyHandler_HandleError_Call {
	return &MockAuthenticatedProxyHandler_HandleError_Call{Call: _e.mock.On("HandleError", err, c)}
}

func (_c *MockAuthenticatedProxyHandler_HandleError_Call) Run(run func(err error, c *fiber.Ctx)) *MockAuthenticatedProxyHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_HandleError_Call) Return(_a0 error) *MockAuthenticatedProxyHandler_HandleError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_HandleError_Call) RunAndReturn(run func(error, *fiber.Ctx) error) *MockAuthenticatedProxyHandler_HandleError_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockAuthenticatedProxyHandler) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuthenticatedProxyHandler_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockAuthenticatedProxyHandler_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockAuthenticatedProxyHandler_Expecter) IsEnabled() *MockAuthenticatedProxyHandler_IsEnabled_Call {
	return &MockAuthenticatedProxyHandler_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockAuthenticatedProxyHandler_IsEnabled_Call) Run(run func()) *MockAuthenticatedProxyHandler_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_IsEnabled_Call) Return(_a0 bool) *MockAuthenticatedProxyHandler_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_IsEnabled_Call) RunAndReturn(run func() bool) *MockAuthenticatedProxyHandler_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldCache provides a mock function with given fields: c, statusCode
func (_m *MockAuthenticatedProxyHandler) ShouldCache(c *fiber.Ctx, statusCode int) bool {
	ret := _m.Called(c, statusCode)

	if len(ret) == 0 {
		panic("no return value specified for ShouldCache")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, int) bool); ok {
		r0 = rf(c, statusCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuthenticatedProxyHandler_ShouldCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldCache'
type MockAuthenticatedProxyHandler_ShouldCache_Call struct {
	*mock.Call
}

// ShouldCache is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - statusCode int
func (_e *MockAuthenticatedProxyHandler_Expecter) ShouldCache(c interface{}, statusCode interface{}) *MockAuthenticatedProxyHandler_ShouldCache_Call {
	return &MockAuthenticatedProxyHandler_ShouldCache_Call{Call: _e.mock.On("ShouldCache", c, statusCode)}
}

func (_c *MockAuthenticatedProxyHandler_ShouldCache_Call) Run(run func(c *fiber.Ctx, statusCode int)) *MockAuthenticatedProxyHandler_ShouldCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(int))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_ShouldCache_Call) Return(_a0 bool) *MockAuthenticatedProxyHandler_ShouldCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_ShouldCache_Call) RunAndReturn(run func(*fiber.Ctx, int) bool) *MockAuthenticatedProxyHandler_ShouldCache_Call {
	_c.Call.Return(run)
	return _c
}

// TransformRequest provides a mock function with given fields: c, upstreamReq
func (_m *MockAuthenticatedProxyHandler) TransformRequest(c *fiber.Ctx, upstreamReq *fiber.Agent) error {
	ret := _m.Called(c, upstreamReq)

	if len(ret) == 0 {
		panic("no return value specified for TransformRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, *fiber.Agent) error); ok {
		r0 = rf(c, upstreamReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthenticatedProxyHandler_TransformRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformRequest'
type MockAuthenticatedProxyHandler_TransformRequest_Call struct {
	*mock.Call
}

// TransformRequest is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - upstreamReq *fiber.Agent
func (_e *MockAuthenticatedProxyHandler_Expecter) TransformRequest(c interface{}, upstreamReq interface{}) *MockAuthenticatedProxyHandler_TransformRequest_Call {
	return &MockAuthenticatedProxyHandler_TransformRequest_Call{Call: _e.mock.On("TransformRequest", c, upstreamReq)}
}

func (_c *MockAuthenticatedProxyHandler_TransformRequest_Call) Run(run func(c *fiber.Ctx, upstreamReq *fiber.Agent)) *MockAuthenticatedProxyHandler_TransformRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(*fiber.Agent))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_TransformRequest_Call) Return(_a0 error) *MockAuthenticatedProxyHandler_TransformRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_TransformRequest_Call) RunAndReturn(run func(*fiber.Ctx, *fiber.Agent) error) *MockAuthenticatedProxyHandler_TransformRequest_Call {
	_c.Call.Return(run)
	return _c
}

// TransformResponse provides a mock function with given fields: resp, c
func (_m *MockAuthenticatedProxyHandler) TransformResponse(resp []byte, c *fiber.Ctx) ([]byte, error) {
	ret := _m.Called(resp, c)

	if len(ret) == 0 {
		panic("no return value specified for TransformResponse")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) ([]byte, error)); ok {
		return rf(resp, c)
	}
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) []byte); ok {
		r0 = rf(resp, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, *fiber.Ctx) error); ok {
		r1 = rf(resp, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticatedProxyHandler_TransformResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformResponse'
type MockAuthenticatedProxyHandler_TransformResponse_Call struct {
	*mock.Call
}

// TransformResponse is a helper method to define mock.On call
//   - resp []byte
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) TransformResponse(resp interface{}, c interface{}) *MockAuthenticatedProxyHandler_TransformResponse_Call {
	return &MockAuthenticatedProxyHandler_TransformResponse_Call{Call: _e.mock.On("TransformResponse", resp, c)}
}

func (_c *MockAuthenticatedProxyHandler_TransformResponse_Call) Run(run func(resp []byte, c *fiber.Ctx)) *MockAuthenticatedProxyHandler_TransformResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_TransformResponse_Call) Return(_a0 []byte, _a1 error) *MockAuthenticatedProxyHandler_TransformResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_TransformResponse_Call) RunAndReturn(run func([]byte, *fiber.Ctx) ([]byte, error)) *MockAuthenticatedProxyHandler_TransformResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockAuthenticatedProxyHandler) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAuthenticatedProxyHandler_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockAuthenticatedProxyHandler_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockAuthenticatedProxyHandler_Expecter) Type() *MockAuthenticatedProxyHandler_Type_Call {
	return &MockAuthenticatedProxyHandler_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockAuthenticatedProxyHandler_Type_Call) Run(run func()) *MockAuthenticatedProxyHandler_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_Type_Call) Return(_a0 string) *MockAuthenticatedProxyHandler_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_Type_Call) RunAndReturn(run func() string) *MockAuthenticatedProxyHandler_Type_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateClientAuth provides a mock function with given fields: c
func (_m *MockAuthenticatedProxyHandler) ValidateClientAuth(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClientAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthenticatedProxyHandler_ValidateClientAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClientAuth'
type MockAuthenticatedProxyHandler_ValidateClientAuth_Call struct {
	*mock.Call
}

// ValidateClientAuth is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockAuthenticatedProxyHandler_Expecter) ValidateClientAuth(c interface{}) *MockAuthenticatedProxyHandler_ValidateClientAuth_Call {
	return &MockAuthenticatedProxyHandler_ValidateClientAuth_Call{Call: _e.mock.On("ValidateClientAuth", c)}
}

func (_c *MockAuthenticatedProxyHandler_ValidateClientAuth_Call) Run(run func(c *fiber.Ctx)) *MockAuthenticatedProxyHandler_ValidateClientAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockAuthenticatedProxyHandler_ValidateClientAuth_Call) Return(_a0 error) *MockAuthenticatedProxyHandler_ValidateClientAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticatedProxyHandler_ValidateClientAuth_Call) RunAndReturn(run func(*fiber.Ctx) error) *MockAuthenticatedProxyHandler_ValidateClientAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticatedProxyHandler creates a new instance of MockAuthenticatedProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticatedProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticatedProxyHandler {
	mock := &MockAuthenticatedProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
