// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCacheableProxyHandler is an autogenerated mock type for the CacheableProxyHandler type
type MockCacheableProxyHandler struct {
	mock.Mock
}

type MockCacheableProxyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheableProxyHandler) EXPECT() *MockCacheableProxyHandler_Expecter {
	return &MockCacheableProxyHandler_Expecter{mock: &_m.Mock}
}

// BuildUpstreamURL provides a mock function with given fields: c
func (_m *MockCacheableProxyHandler) BuildUpstreamURL(c *fiber.Ctx) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for BuildUpstreamURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheableProxyHandler_BuildUpstreamURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildUpstreamURL'
type MockCacheableProxyHandler_BuildUpstreamURL_Call struct {
	*mock.Call
}

// BuildUpstreamURL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) BuildUpstreamURL(c interface{}) *MockCacheableProxyHandler_BuildUpstreamURL_Call {
	return &MockCacheableProxyHandler_BuildUpstreamURL_Call{Call: _e.mock.On("BuildUpstreamURL", c)}
}

func (_c *MockCacheableProxyHandler_BuildUpstreamURL_Call) Run(run func(c *fiber.Ctx)) *MockCacheableProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_BuildUpstreamURL_Call) Return(_a0 string, _a1 error) *MockCacheableProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheableProxyHandler_BuildUpstreamURL_Call) RunAndReturn(run func(*fiber.Ctx) (string, error)) *MockCacheableProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCacheKey provides a mock function with given fields: c
func (_m *MockCacheableProxyHandler) GenerateCacheKey(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCacheKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCacheableProxyHandler_GenerateCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCacheKey'
type MockCacheableProxyHandler_GenerateCacheKey_Call struct {
	*mock.Call
}

// GenerateCacheKey is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) GenerateCacheKey(c interface{}) *MockCacheableProxyHandler_GenerateCacheKey_Call {
	return &MockCacheableProxyHandler_GenerateCacheKey_Call{Call: _e.mock.On("GenerateCacheKey", c)}
}

func (_c *MockCacheableProxyHandler_GenerateCacheKey_Call) Run(run func(c *fiber.Ctx)) *MockCacheableProxyHandler_GenerateCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_GenerateCacheKey_Call) Return(_a0 string) *MockCacheableProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_GenerateCacheKey_Call) RunAndReturn(run func(*fiber.Ctx) string) *MockCacheableProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachePriority provides a mock function with given fields: c
func (_m *MockCacheableProxyHandler) GetCachePriority(c *fiber.Ctx) int {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCachePriority")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) int); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockCacheableProxyHandler_GetCachePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachePriority'
type MockCacheableProxyHandler_GetCachePriority_Call struct {
	*mock.Call
}

// GetCachePriority is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) GetCachePriority(c interface{}) *MockCacheableProxyHandler_GetCachePriority_Call {
	return &MockCacheableProxyHandler_GetCachePriority_Call{Call: _e.mock.On("GetCachePriority", c)}
}

func (_c *MockCacheableProxyHandler_GetCachePriority_Call) Run(run func(c *fiber.Ctx)) *MockCacheableProxyHandler_GetCachePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_GetCachePriority_Call) Return(_a0 int) *MockCacheableProxyHandler_GetCachePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_GetCachePriority_Call) RunAndReturn(run func(*fiber.Ctx) int) *MockCacheableProxyHandler_GetCachePriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheTTL provides a mock function with given fields: c
func (_m *MockCacheableProxyHandler) GetCacheTTL(c *fiber.Ctx) time.Duration {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) time.Duration); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockCacheableProxyHandler_GetCacheTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheTTL'
type MockCacheableProxyHandler_GetCacheTTL_Call struct {
	*mock.Call
}

// GetCacheTTL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) GetCacheTTL(c interface{}) *MockCacheableProxyHandler_GetCacheTTL_Call {
	return &MockCacheableProxyHandler_GetCacheTTL_Call{Call: _e.mock.On("GetCacheTTL", c)}
}

func (_c *MockCacheableProxyHandler_GetCacheTTL_Call) Run(run func(c *fiber.Ctx)) *MockCacheableProxyHandler_GetCacheTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_GetCacheTTL_Call) Return(_a0 time.Duration) *MockCacheableProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_GetCacheTTL_Call) RunAndReturn(run func(*fiber.Ctx) time.Duration) *MockCacheableProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(run)
	return _c
}

// HandleError provides a mock function with given fields: err, c
func (_m *MockCacheableProxyHandler) HandleError(err error, c *fiber.Ctx) error {
	ret := _m.Called(err, c)

	if len(ret) == 0 {
		panic("no return value specified for HandleError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error, *fiber.Ctx) error); ok {
		r0 = rf(err, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheableProxyHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockCacheableProxyHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - err error
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) HandleError(err interface{}, c interface{}) *MockCacheableProxyHandler_HandleError_Call {
	return &MockCacheableProxyHandler_HandleError_Call{Call: _e.mock.On("HandleError", err, c)}
}

func (_c *MockCacheableProxyHandler_HandleError_Call) Run(run func(err error, c *fiber.Ctx)) *MockCacheableProxyHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_HandleError_Call) Return(_a0 error) *MockCacheableProxyHandler_HandleError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_HandleError_Call) RunAndReturn(run func(error, *fiber.Ctx) error) *MockCacheableProxyHandler_HandleError_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockCacheableProxyHandler) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCacheableProxyHandler_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockCacheableProxyHandler_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockCacheableProxyHandler_Expecter) IsEnabled() *MockCacheableProxyHandler_IsEnabled_Call {
	return &MockCacheableProxyHandler_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockCacheableProxyHandler_IsEnabled_Call) Run(run func()) *MockCacheableProxyHandler_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheableProxyHandler_IsEnabled_Call) Return(_a0 bool) *MockCacheableProxyHandler_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_IsEnabled_Call) RunAndReturn(run func() bool) *MockCacheableProxyHandler_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldCache provides a mock function with given fields: c, statusCode
func (_m *MockCacheableProxyHandler) ShouldCache(c *fiber.Ctx, statusCode int) bool {
	ret := _m.Called(c, statusCode)

	if len(ret) == 0 {
		panic("no return value specified for ShouldCache")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, int) bool); ok {
		r0 = rf(c, statusCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCacheableProxyHandler_ShouldCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldCache'
type MockCacheableProxyHandler_ShouldCache_Call struct {
	*mock.Call
}

// ShouldCache is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - statusCode int
func (_e *MockCacheableProxyHandler_Expecter) ShouldCache(c interface{}, statusCode interface{}) *MockCacheableProxyHandler_ShouldCache_Call {
	return &MockCacheableProxyHandler_ShouldCache_Call{Call: _e.mock.On("ShouldCache", c, statusCode)}
}

func (_c *MockCacheableProxyHandler_ShouldCache_Call) Run(run func(c *fiber.Ctx, statusCode int)) *MockCacheableProxyHandler_ShouldCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(int))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_ShouldCache_Call) Return(_a0 bool) *MockCacheableProxyHandler_ShouldCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_ShouldCache_Call) RunAndReturn(run func(*fiber.Ctx, int) bool) *MockCacheableProxyHandler_ShouldCache_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldInvalidateCache provides a mock function with given fields: c
func (_m *MockCacheableProxyHandler) ShouldInvalidateCache(c *fiber.Ctx) bool {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ShouldInvalidateCache")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) bool); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCacheableProxyHandler_ShouldInvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldInvalidateCache'
type MockCacheableProxyHandler_ShouldInvalidateCache_Call struct {
	*mock.Call
}

// ShouldInvalidateCache is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) ShouldInvalidateCache(c interface{}) *MockCacheableProxyHandler_ShouldInvalidateCache_Call {
	return &MockCacheableProxyHandler_ShouldInvalidateCache_Call{Call: _e.mock.On("ShouldInvalidateCache", c)}
}

func (_c *MockCacheableProxyHandler_ShouldInvalidateCache_Call) Run(run func(c *fiber.Ctx)) *MockCacheableProxyHandler_ShouldInvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_ShouldInvalidateCache_Call) Return(_a0 bool) *MockCacheableProxyHandler_ShouldInvalidateCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_ShouldInvalidateCache_Call) RunAndReturn(run func(*fiber.Ctx) bool) *MockCacheableProxyHandler_ShouldInvalidateCache_Call {
	_c.Call.Return(run)
	return _c
}

// TransformRequest provides a mock function with given fields: c, upstreamReq
func (_m *MockCacheableProxyHandler) TransformRequest(c *fiber.Ctx, upstreamReq *fiber.Agent) error {
	ret := _m.Called(c, upstreamReq)

	if len(ret) == 0 {
		panic("no return value specified for TransformRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, *fiber.Agent) error); ok {
		r0 = rf(c, upstreamReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheableProxyHandler_TransformRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformRequest'
type MockCacheableProxyHandler_TransformRequest_Call struct {
	*mock.Call
}

// TransformRequest is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - upstreamReq *fiber.Agent
func (_e *MockCacheableProxyHandler_Expecter) TransformRequest(c interface{}, upstreamReq interface{}) *MockCacheableProxyHandler_TransformRequest_Call {
	return &MockCacheableProxyHandler_TransformRequest_Call{Call: _e.mock.On("TransformRequest", c, upstreamReq)}
}

func (_c *MockCacheableProxyHandler_TransformRequest_Call) Run(run func(c *fiber.Ctx, upstreamReq *fiber.Agent)) *MockCacheableProxyHandler_TransformRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(*fiber.Agent))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_TransformRequest_Call) Return(_a0 error) *MockCacheableProxyHandler_TransformRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_TransformRequest_Call) RunAndReturn(run func(*fiber.Ctx, *fiber.Agent) error) *MockCacheableProxyHandler_TransformRequest_Call {
	_c.Call.Return(run)
	return _c
}

// TransformResponse provides a mock function with given fields: resp, c
func (_m *MockCacheableProxyHandler) TransformResponse(resp []byte, c *fiber.Ctx) ([]byte, error) {
	ret := _m.Called(resp, c)

	if len(ret) == 0 {
		panic("no return value specified for TransformResponse")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) ([]byte, error)); ok {
		return rf(resp, c)
	}
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) []byte); ok {
		r0 = rf(resp, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, *fiber.Ctx) error); ok {
		r1 = rf(resp, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheableProxyHandler_TransformResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformResponse'
type MockCacheableProxyHandler_TransformResponse_Call struct {
	*mock.Call
}

// TransformResponse is a helper method to define mock.On call
//   - resp []byte
//   - c *fiber.Ctx
func (_e *MockCacheableProxyHandler_Expecter) TransformResponse(resp interface{}, c interface{}) *MockCacheableProxyHandler_TransformResponse_Call {
	return &MockCacheableProxyHandler_TransformResponse_Call{Call: _e.mock.On("TransformResponse", resp, c)}
}

func (_c *MockCacheableProxyHandler_TransformResponse_Call) Run(run func(resp []byte, c *fiber.Ctx)) *MockCacheableProxyHandler_TransformResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockCacheableProxyHandler_TransformResponse_Call) Return(_a0 []byte, _a1 error) *MockCacheableProxyHandler_TransformResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheableProxyHandler_TransformResponse_Call) RunAndReturn(run func([]byte, *fiber.Ctx) ([]byte, error)) *MockCacheableProxyHandler_TransformResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockCacheableProxyHandler) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCacheableProxyHandler_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockCacheableProxyHandler_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockCacheableProxyHandler_Expecter) Type() *MockCacheableProxyHandler_Type_Call {
	return &MockCacheableProxyHandler_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockCacheableProxyHandler_Type_Call) Run(run func()) *MockCacheableProxyHandler_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheableProxyHandler_Type_Call) Return(_a0 string) *MockCacheableProxyHandler_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheableProxyHandler_Type_Call) RunAndReturn(run func() string) *MockCacheableProxyHandler_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheableProxyHandler creates a new instance of MockCacheableProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheableProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheableProxyHandler {
	mock := &MockCacheableProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
