// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockHealthable is an autogenerated mock type for the Healthable type
type MockHealthable struct {
	mock.Mock
}

type MockHealthable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthable) EXPECT() *MockHealthable_Expecter {
	return &MockHealthable_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function with no fields
func (_m *MockHealthable) HealthCheck() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthable_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockHealthable_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockHealthable_Expecter) HealthCheck() *MockHealthable_HealthCheck_Call {
	return &MockHealthable_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockHealthable_HealthCheck_Call) Run(run func()) *MockHealthable_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthable_HealthCheck_Call) Return(_a0 error) *MockHealthable_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthable_HealthCheck_Call) RunAndReturn(run func() error) *MockHealthable_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthable creates a new instance of MockHealthable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthable {
	mock := &MockHealthable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
