// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockMetricsAwareProxyHandler is an autogenerated mock type for the MetricsAwareProxyHandler type
type MockMetricsAwareProxyHandler struct {
	mock.Mock
}

type MockMetricsAwareProxyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsAwareProxyHandler) EXPECT() *MockMetricsAwareProxyHandler_Expecter {
	return &MockMetricsAwareProxyHandler_Expecter{mock: &_m.Mock}
}

// BuildUpstreamURL provides a mock function with given fields: c
func (_m *MockMetricsAwareProxyHandler) BuildUpstreamURL(c *fiber.Ctx) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for BuildUpstreamURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsAwareProxyHandler_BuildUpstreamURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildUpstreamURL'
type MockMetricsAwareProxyHandler_BuildUpstreamURL_Call struct {
	*mock.Call
}

// BuildUpstreamURL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockMetricsAwareProxyHandler_Expecter) BuildUpstreamURL(c interface{}) *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call {
	return &MockMetricsAwareProxyHandler_BuildUpstreamURL_Call{Call: _e.mock.On("BuildUpstreamURL", c)}
}

func (_c *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call) Run(run func(c *fiber.Ctx)) *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call) Return(_a0 string, _a1 error) *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call) RunAndReturn(run func(*fiber.Ctx) (string, error)) *MockMetricsAwareProxyHandler_BuildUpstreamURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCacheKey provides a mock function with given fields: c
func (_m *MockMetricsAwareProxyHandler) GenerateCacheKey(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCacheKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMetricsAwareProxyHandler_GenerateCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCacheKey'
type MockMetricsAwareProxyHandler_GenerateCacheKey_Call struct {
	*mock.Call
}

// GenerateCacheKey is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockMetricsAwareProxyHandler_Expecter) GenerateCacheKey(c interface{}) *MockMetricsAwareProxyHandler_GenerateCacheKey_Call {
	return &MockMetricsAwareProxyHandler_GenerateCacheKey_Call{Call: _e.mock.On("GenerateCacheKey", c)}
}

func (_c *MockMetricsAwareProxyHandler_GenerateCacheKey_Call) Run(run func(c *fiber.Ctx)) *MockMetricsAwareProxyHandler_GenerateCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_GenerateCacheKey_Call) Return(_a0 string) *MockMetricsAwareProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_GenerateCacheKey_Call) RunAndReturn(run func(*fiber.Ctx) string) *MockMetricsAwareProxyHandler_GenerateCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheTTL provides a mock function with given fields: c
func (_m *MockMetricsAwareProxyHandler) GetCacheTTL(c *fiber.Ctx) time.Duration {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) time.Duration); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockMetricsAwareProxyHandler_GetCacheTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheTTL'
type MockMetricsAwareProxyHandler_GetCacheTTL_Call struct {
	*mock.Call
}

// GetCacheTTL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockMetricsAwareProxyHandler_Expecter) GetCacheTTL(c interface{}) *MockMetricsAwareProxyHandler_GetCacheTTL_Call {
	return &MockMetricsAwareProxyHandler_GetCacheTTL_Call{Call: _e.mock.On("GetCacheTTL", c)}
}

func (_c *MockMetricsAwareProxyHandler_GetCacheTTL_Call) Run(run func(c *fiber.Ctx)) *MockMetricsAwareProxyHandler_GetCacheTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_GetCacheTTL_Call) Return(_a0 time.Duration) *MockMetricsAwareProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_GetCacheTTL_Call) RunAndReturn(run func(*fiber.Ctx) time.Duration) *MockMetricsAwareProxyHandler_GetCacheTTL_Call {
	_c.Call.Return(run)
	return _c
}

// HandleError provides a mock function with given fields: err, c
func (_m *MockMetricsAwareProxyHandler) HandleError(err error, c *fiber.Ctx) error {
	ret := _m.Called(err, c)

	if len(ret) == 0 {
		panic("no return value specified for HandleError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error, *fiber.Ctx) error); ok {
		r0 = rf(err, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsAwareProxyHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockMetricsAwareProxyHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - err error
//   - c *fiber.Ctx
func (_e *MockMetricsAwareProxyHandler_Expecter) HandleError(err interface{}, c interface{}) *MockMetricsAwareProxyHandler_HandleError_Call {
	return &MockMetricsAwareProxyHandler_HandleError_Call{Call: _e.mock.On("HandleError", err, c)}
}

func (_c *MockMetricsAwareProxyHandler_HandleError_Call) Run(run func(err error, c *fiber.Ctx)) *MockMetricsAwareProxyHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_HandleError_Call) Return(_a0 error) *MockMetricsAwareProxyHandler_HandleError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_HandleError_Call) RunAndReturn(run func(error, *fiber.Ctx) error) *MockMetricsAwareProxyHandler_HandleError_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockMetricsAwareProxyHandler) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMetricsAwareProxyHandler_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockMetricsAwareProxyHandler_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockMetricsAwareProxyHandler_Expecter) IsEnabled() *MockMetricsAwareProxyHandler_IsEnabled_Call {
	return &MockMetricsAwareProxyHandler_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockMetricsAwareProxyHandler_IsEnabled_Call) Run(run func()) *MockMetricsAwareProxyHandler_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_IsEnabled_Call) Return(_a0 bool) *MockMetricsAwareProxyHandler_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_IsEnabled_Call) RunAndReturn(run func() bool) *MockMetricsAwareProxyHandler_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCacheMetrics provides a mock function with given fields: cacheKey, hit, size
func (_m *MockMetricsAwareProxyHandler) RecordCacheMetrics(cacheKey string, hit bool, size int) {
	_m.Called(cacheKey, hit, size)
}

// MockMetricsAwareProxyHandler_RecordCacheMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCacheMetrics'
type MockMetricsAwareProxyHandler_RecordCacheMetrics_Call struct {
	*mock.Call
}

// RecordCacheMetrics is a helper method to define mock.On call
//   - cacheKey string
//   - hit bool
//   - size int
func (_e *MockMetricsAwareProxyHandler_Expecter) RecordCacheMetrics(cacheKey interface{}, hit interface{}, size interface{}) *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call {
	return &MockMetricsAwareProxyHandler_RecordCacheMetrics_Call{Call: _e.mock.On("RecordCacheMetrics", cacheKey, hit, size)}
}

func (_c *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call) Run(run func(cacheKey string, hit bool, size int)) *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool), args[2].(int))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call) Return() *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call) RunAndReturn(run func(string, bool, int)) *MockMetricsAwareProxyHandler_RecordCacheMetrics_Call {
	_c.Run(run)
	return _c
}

// RecordRequestMetrics provides a mock function with given fields: c, statusCode, duration
func (_m *MockMetricsAwareProxyHandler) RecordRequestMetrics(c *fiber.Ctx, statusCode int, duration time.Duration) {
	_m.Called(c, statusCode, duration)
}

// MockMetricsAwareProxyHandler_RecordRequestMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRequestMetrics'
type MockMetricsAwareProxyHandler_RecordRequestMetrics_Call struct {
	*mock.Call
}

// RecordRequestMetrics is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - statusCode int
//   - duration time.Duration
func (_e *MockMetricsAwareProxyHandler_Expecter) RecordRequestMetrics(c interface{}, statusCode interface{}, duration interface{}) *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call {
	return &MockMetricsAwareProxyHandler_RecordRequestMetrics_Call{Call: _e.mock.On("RecordRequestMetrics", c, statusCode, duration)}
}

func (_c *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call) Run(run func(c *fiber.Ctx, statusCode int, duration time.Duration)) *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(int), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call) Return() *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call) RunAndReturn(run func(*fiber.Ctx, int, time.Duration)) *MockMetricsAwareProxyHandler_RecordRequestMetrics_Call {
	_c.Run(run)
	return _c
}

// ShouldCache provides a mock function with given fields: c, statusCode
func (_m *MockMetricsAwareProxyHandler) ShouldCache(c *fiber.Ctx, statusCode int) bool {
	ret := _m.Called(c, statusCode)

	if len(ret) == 0 {
		panic("no return value specified for ShouldCache")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, int) bool); ok {
		r0 = rf(c, statusCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMetricsAwareProxyHandler_ShouldCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldCache'
type MockMetricsAwareProxyHandler_ShouldCache_Call struct {
	*mock.Call
}

// ShouldCache is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - statusCode int
func (_e *MockMetricsAwareProxyHandler_Expecter) ShouldCache(c interface{}, statusCode interface{}) *MockMetricsAwareProxyHandler_ShouldCache_Call {
	return &MockMetricsAwareProxyHandler_ShouldCache_Call{Call: _e.mock.On("ShouldCache", c, statusCode)}
}

func (_c *MockMetricsAwareProxyHandler_ShouldCache_Call) Run(run func(c *fiber.Ctx, statusCode int)) *MockMetricsAwareProxyHandler_ShouldCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(int))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_ShouldCache_Call) Return(_a0 bool) *MockMetricsAwareProxyHandler_ShouldCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_ShouldCache_Call) RunAndReturn(run func(*fiber.Ctx, int) bool) *MockMetricsAwareProxyHandler_ShouldCache_Call {
	_c.Call.Return(run)
	return _c
}

// TransformRequest provides a mock function with given fields: c, upstreamReq
func (_m *MockMetricsAwareProxyHandler) TransformRequest(c *fiber.Ctx, upstreamReq *fiber.Agent) error {
	ret := _m.Called(c, upstreamReq)

	if len(ret) == 0 {
		panic("no return value specified for TransformRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx, *fiber.Agent) error); ok {
		r0 = rf(c, upstreamReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsAwareProxyHandler_TransformRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformRequest'
type MockMetricsAwareProxyHandler_TransformRequest_Call struct {
	*mock.Call
}

// TransformRequest is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - upstreamReq *fiber.Agent
func (_e *MockMetricsAwareProxyHandler_Expecter) TransformRequest(c interface{}, upstreamReq interface{}) *MockMetricsAwareProxyHandler_TransformRequest_Call {
	return &MockMetricsAwareProxyHandler_TransformRequest_Call{Call: _e.mock.On("TransformRequest", c, upstreamReq)}
}

func (_c *MockMetricsAwareProxyHandler_TransformRequest_Call) Run(run func(c *fiber.Ctx, upstreamReq *fiber.Agent)) *MockMetricsAwareProxyHandler_TransformRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx), args[1].(*fiber.Agent))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_TransformRequest_Call) Return(_a0 error) *MockMetricsAwareProxyHandler_TransformRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_TransformRequest_Call) RunAndReturn(run func(*fiber.Ctx, *fiber.Agent) error) *MockMetricsAwareProxyHandler_TransformRequest_Call {
	_c.Call.Return(run)
	return _c
}

// TransformResponse provides a mock function with given fields: resp, c
func (_m *MockMetricsAwareProxyHandler) TransformResponse(resp []byte, c *fiber.Ctx) ([]byte, error) {
	ret := _m.Called(resp, c)

	if len(ret) == 0 {
		panic("no return value specified for TransformResponse")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) ([]byte, error)); ok {
		return rf(resp, c)
	}
	if rf, ok := ret.Get(0).(func([]byte, *fiber.Ctx) []byte); ok {
		r0 = rf(resp, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, *fiber.Ctx) error); ok {
		r1 = rf(resp, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsAwareProxyHandler_TransformResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformResponse'
type MockMetricsAwareProxyHandler_TransformResponse_Call struct {
	*mock.Call
}

// TransformResponse is a helper method to define mock.On call
//   - resp []byte
//   - c *fiber.Ctx
func (_e *MockMetricsAwareProxyHandler_Expecter) TransformResponse(resp interface{}, c interface{}) *MockMetricsAwareProxyHandler_TransformResponse_Call {
	return &MockMetricsAwareProxyHandler_TransformResponse_Call{Call: _e.mock.On("TransformResponse", resp, c)}
}

func (_c *MockMetricsAwareProxyHandler_TransformResponse_Call) Run(run func(resp []byte, c *fiber.Ctx)) *MockMetricsAwareProxyHandler_TransformResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_TransformResponse_Call) Return(_a0 []byte, _a1 error) *MockMetricsAwareProxyHandler_TransformResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_TransformResponse_Call) RunAndReturn(run func([]byte, *fiber.Ctx) ([]byte, error)) *MockMetricsAwareProxyHandler_TransformResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockMetricsAwareProxyHandler) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMetricsAwareProxyHandler_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockMetricsAwareProxyHandler_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockMetricsAwareProxyHandler_Expecter) Type() *MockMetricsAwareProxyHandler_Type_Call {
	return &MockMetricsAwareProxyHandler_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockMetricsAwareProxyHandler_Type_Call) Run(run func()) *MockMetricsAwareProxyHandler_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsAwareProxyHandler_Type_Call) Return(_a0 string) *MockMetricsAwareProxyHandler_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsAwareProxyHandler_Type_Call) RunAndReturn(run func() string) *MockMetricsAwareProxyHandler_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsAwareProxyHandler creates a new instance of MockMetricsAwareProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsAwareProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsAwareProxyHandler {
	mock := &MockMetricsAwareProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
