// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockProxyHandler is an autogenerated mock type for the ProxyHandler type
type MockProxyHandler struct {
	mock.Mock
}

type MockProxyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProxyHandler) EXPECT() *MockProxyHandler_Expecter {
	return &MockProxyHandler_Expecter{mock: &_m.Mock}
}

// GetCacheKey provides a mock function with given fields: c
func (_m *MockProxyHandler) GetCacheKey(c *fiber.Ctx) string {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProxyHandler_GetCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheKey'
type MockProxyHandler_GetCacheKey_Call struct {
	*mock.Call
}

// GetCacheKey is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) GetCacheKey(c interface{}) *MockProxyHandler_GetCacheKey_Call {
	return &MockProxyHandler_GetCacheKey_Call{Call: _e.mock.On("GetCacheKey", c)}
}

func (_c *MockProxyHandler_GetCacheKey_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_GetCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_GetCacheKey_Call) Return(_a0 string) *MockProxyHandler_GetCacheKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_GetCacheKey_Call) RunAndReturn(run func(*fiber.Ctx) string) *MockProxyHandler_GetCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpstreamURL provides a mock function with given fields: c
func (_m *MockProxyHandler) GetUpstreamURL(c *fiber.Ctx) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetUpstreamURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProxyHandler_GetUpstreamURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpstreamURL'
type MockProxyHandler_GetUpstreamURL_Call struct {
	*mock.Call
}

// GetUpstreamURL is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) GetUpstreamURL(c interface{}) *MockProxyHandler_GetUpstreamURL_Call {
	return &MockProxyHandler_GetUpstreamURL_Call{Call: _e.mock.On("GetUpstreamURL", c)}
}

func (_c *MockProxyHandler_GetUpstreamURL_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_GetUpstreamURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_GetUpstreamURL_Call) Return(_a0 string, _a1 error) *MockProxyHandler_GetUpstreamURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProxyHandler_GetUpstreamURL_Call) RunAndReturn(run func(*fiber.Ctx) (string, error)) *MockProxyHandler_GetUpstreamURL_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: c
func (_m *MockProxyHandler) Handle(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProxyHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockProxyHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) Handle(c interface{}) *MockProxyHandler_Handle_Call {
	return &MockProxyHandler_Handle_Call{Call: _e.mock.On("Handle", c)}
}

func (_c *MockProxyHandler_Handle_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_Handle_Call) Return(_a0 error) *MockProxyHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_Handle_Call) RunAndReturn(run func(*fiber.Ctx) error) *MockProxyHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with no fields
func (_m *MockProxyHandler) HealthCheck() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProxyHandler_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockProxyHandler_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockProxyHandler_Expecter) HealthCheck() *MockProxyHandler_HealthCheck_Call {
	return &MockProxyHandler_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockProxyHandler_HealthCheck_Call) Run(run func()) *MockProxyHandler_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProxyHandler_HealthCheck_Call) Return(_a0 error) *MockProxyHandler_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_HealthCheck_Call) RunAndReturn(run func() error) *MockProxyHandler_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// IsCacheable provides a mock function with given fields: c
func (_m *MockProxyHandler) IsCacheable(c *fiber.Ctx) bool {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for IsCacheable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) bool); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProxyHandler_IsCacheable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCacheable'
type MockProxyHandler_IsCacheable_Call struct {
	*mock.Call
}

// IsCacheable is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) IsCacheable(c interface{}) *MockProxyHandler_IsCacheable_Call {
	return &MockProxyHandler_IsCacheable_Call{Call: _e.mock.On("IsCacheable", c)}
}

func (_c *MockProxyHandler_IsCacheable_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_IsCacheable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_IsCacheable_Call) Return(_a0 bool) *MockProxyHandler_IsCacheable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_IsCacheable_Call) RunAndReturn(run func(*fiber.Ctx) bool) *MockProxyHandler_IsCacheable_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyRequest provides a mock function with given fields: c
func (_m *MockProxyHandler) ModifyRequest(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ModifyRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProxyHandler_ModifyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyRequest'
type MockProxyHandler_ModifyRequest_Call struct {
	*mock.Call
}

// ModifyRequest is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) ModifyRequest(c interface{}) *MockProxyHandler_ModifyRequest_Call {
	return &MockProxyHandler_ModifyRequest_Call{Call: _e.mock.On("ModifyRequest", c)}
}

func (_c *MockProxyHandler_ModifyRequest_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_ModifyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_ModifyRequest_Call) Return(_a0 error) *MockProxyHandler_ModifyRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_ModifyRequest_Call) RunAndReturn(run func(*fiber.Ctx) error) *MockProxyHandler_ModifyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyResponse provides a mock function with given fields: c
func (_m *MockProxyHandler) ModifyResponse(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ModifyResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProxyHandler_ModifyResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyResponse'
type MockProxyHandler_ModifyResponse_Call struct {
	*mock.Call
}

// ModifyResponse is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockProxyHandler_Expecter) ModifyResponse(c interface{}) *MockProxyHandler_ModifyResponse_Call {
	return &MockProxyHandler_ModifyResponse_Call{Call: _e.mock.On("ModifyResponse", c)}
}

func (_c *MockProxyHandler_ModifyResponse_Call) Run(run func(c *fiber.Ctx)) *MockProxyHandler_ModifyResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *MockProxyHandler_ModifyResponse_Call) Return(_a0 error) *MockProxyHandler_ModifyResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_ModifyResponse_Call) RunAndReturn(run func(*fiber.Ctx) error) *MockProxyHandler_ModifyResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockProxyHandler) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProxyHandler_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProxyHandler_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProxyHandler_Expecter) Name() *MockProxyHandler_Name_Call {
	return &MockProxyHandler_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProxyHandler_Name_Call) Run(run func()) *MockProxyHandler_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProxyHandler_Name_Call) Return(_a0 string) *MockProxyHandler_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_Name_Call) RunAndReturn(run func() string) *MockProxyHandler_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockProxyHandler) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProxyHandler_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockProxyHandler_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockProxyHandler_Expecter) Type() *MockProxyHandler_Type_Call {
	return &MockProxyHandler_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockProxyHandler_Type_Call) Run(run func()) *MockProxyHandler_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProxyHandler_Type_Call) Return(_a0 string) *MockProxyHandler_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProxyHandler_Type_Call) RunAndReturn(run func() string) *MockProxyHandler_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProxyHandler creates a new instance of MockProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProxyHandler {
	mock := &MockProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
